-- Translation of SQL files into en_GB
-- Format: Original, Language, Translation

-- menus.sql in en_GB
SELECT addTraduction('Abattement intérêts / pénalités', 'en_GB', 'Interest / penalty allowance');
SELECT addTraduction('Affichage attente crédit', 'en_GB', 'Display credit hold');
SELECT addTraduction('Affichage des garanties', 'en_GB', 'Display guarantees');
SELECT addTraduction('Affichage des échéances', 'en_GB', 'Display due dates');
SELECT addTraduction('Affichage mouvements réciproques', 'en_GB', 'Display reciprocal transactions');
SELECT addTraduction('Affichage proposition', 'en_GB', 'Display proposal');
SELECT addTraduction('Ajout Opérations auxiliaires', 'en_GB', 'Add auxiliary operations');
SELECT addTraduction('Ajout Opérations diverses', 'en_GB', 'Add various operations');
SELECT addTraduction('Ajout code', 'en_GB', 'Add code');
SELECT addTraduction('Ajout contrepartie', 'en_GB', 'Add offset');
SELECT addTraduction('Ajout d''une garantie', 'en_GB', 'Add a guarantee');
SELECT addTraduction('Ajout de garantie', 'en_GB', 'Add a guarantee');
SELECT addTraduction('Ajout de garanties', 'en_GB', 'Add guarantees');
SELECT addTraduction('Ajout de journaux', 'en_GB', 'Add journals');
SELECT addTraduction('Ajout de liaison', 'en_GB', 'Add reciprocal account');
SELECT addTraduction('Ajout profil', 'en_GB', 'Add profile');
SELECT addTraduction('Ajout utilisateur', 'en_GB', 'Add user');
SELECT addTraduction('Ajustement encaisse', 'en_GB', 'Cash balance adjustment');
SELECT addTraduction('Ajustement solde compte', 'en_GB', 'Account balance adjustment');
SELECT addTraduction('Annulation dossier de crédit', 'en_GB', 'Cancellation of a loan file');
SELECT addTraduction('Annulation du dossier de crédit', 'en_GB', 'Cancellation of the loan file');
SELECT addTraduction('Annulation mouvements réciproques', 'en_GB', 'Cancellation of reciprocal transactions');
SELECT addTraduction('Appel à l''assurance', 'en_GB', 'Request for insurance');
SELECT addTraduction('Approbation dossier de crédit', 'en_GB', 'Approval of a loan file');
SELECT addTraduction('Approvisionnement', 'en_GB', 'Provisioning');
SELECT addTraduction('Arrêté compte de base', 'en_GB', 'Basic account ruling and balancing');
SELECT addTraduction('Arrêté des comptes', 'en_GB', 'Year-end closing of accounts');
SELECT addTraduction('Attente de Recharge', 'en_GB', 'Pending reload');
SELECT addTraduction('Blocage des garanties', 'en_GB', 'Freezing of guarantees');
SELECT addTraduction('Bloquer / débloquer compte', 'en_GB', 'Freeze / unfreeze account');
SELECT addTraduction('Calcul de la balance', 'en_GB', 'Balance calculation');
SELECT addTraduction('Calcul de provision ', 'en_GB', 'Provision calculation');
SELECT addTraduction('Change cash', 'en_GB', 'Cash exchange');
SELECT addTraduction('Choix compte source', 'en_GB', 'Choosing source account');
SELECT addTraduction('Choix date', 'en_GB', 'Choosing date');
SELECT addTraduction('Choix des comptes', 'en_GB', 'Choosing accounts');
SELECT addTraduction('Choix des informations', 'en_GB', 'Choosing information');
SELECT addTraduction('Choix des remboursements', 'en_GB', 'Choosing reimbursements');
SELECT addTraduction('Choix du compte centralisateur', 'en_GB', 'Choosing the concentration account');
SELECT addTraduction('Choix du compte source', 'en_GB', 'Choosing a source account');
SELECT addTraduction('Choix du compte', 'en_GB', 'Choosing the account');
SELECT addTraduction('Choix du nom', 'en_GB', 'Choosing the name');
SELECT addTraduction('Choix du produit', 'en_GB', 'Choosing the product');
SELECT addTraduction('Choix mandat', 'en_GB', 'Choosing mandate');
SELECT addTraduction('Choix opération diverse', 'en_GB', 'Choosing miscellaneous operation');
SELECT addTraduction('Choix opération', 'en_GB', 'Choosing operation');
SELECT addTraduction('Choix relation', 'en_GB', 'Choosing relationship');
SELECT addTraduction('Choix écriture', 'en_GB', 'Choosing entry');
SELECT addTraduction('Chèques', 'en_GB', 'Checks');
SELECT addTraduction('Clôture compte', 'en_GB', 'Closing of account');
SELECT addTraduction('Clôture exercice', 'en_GB', 'Year end closing');
SELECT addTraduction('Clôture périodique', 'en_GB', 'Periodic closing');
SELECT addTraduction('Commande chèquier', 'en_GB', 'Check book order');
SELECT addTraduction('Comptabilité', 'en_GB', 'Accounting');
SELECT addTraduction('Comptes de liaison', 'en_GB', 'Reciprocal accounts');
SELECT addTraduction('Confirmation Autorisation', 'en_GB', 'Confirmation of authorization');
SELECT addTraduction('Confirmation Clôture', 'en_GB', 'Confirmation of closing');
SELECT addTraduction('Confirmation ajout garantie', 'en_GB', 'Confirmation of addition of guarantee');
SELECT addTraduction('Confirmation ajout', 'en_GB', 'Confirmation of addition');
SELECT addTraduction('Confirmation annulation', 'en_GB', 'Confirmation of cancellation');
SELECT addTraduction('Confirmation clôture', 'en_GB', 'Confirmation of closing');
SELECT addTraduction('Confirmation creation compte', 'en_GB', 'Confirmation of account creation');
SELECT addTraduction('Confirmation création compte', 'en_GB', 'Confirmation of account creation');
SELECT addTraduction('Confirmation de Recharge', 'en_GB', 'Confirmation of reload');
SELECT addTraduction('Confirmation de l''échéancier', 'en_GB', 'Confirmation of schedule');
SELECT addTraduction('Confirmation de la réalisation', 'en_GB', 'Confirmation of realization');
SELECT addTraduction('Confirmation déconnexion', 'en_GB', 'Confirmation of logout');
SELECT addTraduction('Confirmation défection', 'en_GB', 'Confirmation of abandonment');
SELECT addTraduction('Confirmation dépôt', 'en_GB', 'Confirmation of deposit');
SELECT addTraduction('Confirmation garantie', 'en_GB', 'Confirmation of guarantee');
SELECT addTraduction('Confirmation modification', 'en_GB', 'Confirmation of modification');
SELECT addTraduction('Confirmation montant', 'en_GB', 'Confirmation of amount');
SELECT addTraduction('Confirmation remise', 'en_GB', 'Confirmation of discount');
SELECT addTraduction('Confirmation retrait', 'en_GB', 'Confirmation of the withdrawal');
SELECT addTraduction('Confirmation saisie', 'en_GB', 'Confirmation of data entry');
SELECT addTraduction('Confirmation suppression', 'en_GB', 'Confirmation of deletion');
SELECT addTraduction('Confirmation transfert', 'en_GB', 'Confirmation of transfer');
SELECT addTraduction('Confirmation versement', 'en_GB', 'Confirmation of payment');
SELECT addTraduction('Confirmation', 'en_GB', 'Confirmation');
SELECT addTraduction('Consolidation de données', 'en_GB', 'Consolidation of data');
SELECT addTraduction('Consolidation des données', 'en_GB', 'Consolidation of data');
SELECT addTraduction('Consultation client', 'en_GB', 'View client');
SELECT addTraduction('Consultation code utilisateur', 'en_GB', 'View user code');
SELECT addTraduction('Consultation code', 'en_GB', 'View code');
SELECT addTraduction('Consultation compte', 'en_GB', 'View account');
SELECT addTraduction('Consultation des garanties', 'en_GB', 'View guarantees');
SELECT addTraduction('Consultation des journaux', 'en_GB', 'View journals');
SELECT addTraduction('Consultation dossier de crédit', 'en_GB', 'View loan file');
SELECT addTraduction('Consultation dossier', 'en_GB', 'View file');
SELECT addTraduction('Consultation profil', 'en_GB', 'View profile');
SELECT addTraduction('Consultation utilisateur', 'en_GB', 'View user');
SELECT addTraduction('Consultation échéancier', 'en_GB', 'View schedule');
SELECT addTraduction('Consultation', 'en_GB', 'View');
SELECT addTraduction('Correction d''un dossier de crédit', 'en_GB', 'Correction to a loan file');
SELECT addTraduction('Critères affissage', 'en_GB', 'Display criteria');
SELECT addTraduction('Critères de recherche', 'en_GB', 'Search criteria');
SELECT addTraduction('Création client', 'en_GB', 'Create client');
SELECT addTraduction('Création/Modification', 'en_GB', 'Create/Modification');
SELECT addTraduction('Demande Autorisation', 'en_GB', 'Authorization Request');
SELECT addTraduction('Demande confirmation', 'en_GB', 'Confirmation request');
SELECT addTraduction('Données personnelles', 'en_GB', 'Personal data');
SELECT addTraduction('Déboursement des fonds ', 'en_GB', 'Disbursement of funds');
SELECT addTraduction('Déboursement des fonds', 'en_GB', 'Disbursement of funds');
SELECT addTraduction('Déconnexion autre code utilisateur', 'en_GB', 'Disconnection of other user code');
SELECT addTraduction('Défection client', 'en_GB', 'Client abandonment');
SELECT addTraduction('Délestage', 'en_GB', 'Offloading');
SELECT addTraduction('Dépôt express', 'en_GB', 'Express deposit');
SELECT addTraduction('Dépôt par lot via fichier', 'en_GB', 'Confirmation of batch deposit via file');
SELECT addTraduction('Dépôt par lot', 'en_GB', 'Batch deposit');
SELECT addTraduction('Dépôt', 'en_GB', 'Deposit');
SELECT addTraduction('Détail message SWIFT', 'en_GB', 'SWIFT message detail');
SELECT addTraduction('Echéancier réel', 'en_GB', 'Real schedule');
SELECT addTraduction('Echéancier théorique', 'en_GB', 'Notional schedule');
SELECT addTraduction('Enregistrement opération', 'en_GB', 'Confirmation of operation');
SELECT addTraduction('Enregistrement', 'en_GB', 'Record');
SELECT addTraduction('Enrer nouveau solde', 'en_GB', 'Enter new balance');
SELECT addTraduction('Etat', 'en_GB', 'Status');
SELECT addTraduction('Export CSV', 'en_GB', 'CSV Export');
SELECT addTraduction('Export données', 'en_GB', 'Data export');
SELECT addTraduction('Extraits de compte', 'en_GB', 'Account extracts');
SELECT addTraduction('Fermeture', 'en_GB', 'Closing');
SELECT addTraduction('Finalisation défection client', 'en_GB', 'Finalizing client abandonment');
SELECT addTraduction('Frais commande', 'en_GB', 'Order fees');
SELECT addTraduction('Frais de dossier découvert', 'en_GB', 'Account overdraft fee');
SELECT addTraduction('Frais en attente', 'en_GB', 'Fees on hold');
SELECT addTraduction('Gestion Client', 'en_GB', 'Client management');
SELECT addTraduction('Gestion contrepartie', 'en_GB', 'Manage offset');
SELECT addTraduction('Gestion de la licence', 'en_GB', 'Manage the license');
SELECT addTraduction('Gestion des codes utilisateurs', 'en_GB', 'Manage users'' codes');
SELECT addTraduction('Gestion des devises', 'en_GB', 'Manage currencies');
SELECT addTraduction('Gestion des exercices', 'en_GB', 'Manage fiscal years');
SELECT addTraduction('Gestion des garanties', 'en_GB', 'Manage guarantees');
SELECT addTraduction('Gestion des journaux', 'en_GB', 'Manage journals');
SELECT addTraduction('Gestion des mandats', 'en_GB', 'Manage mandates');
SELECT addTraduction('Gestion des profils', 'en_GB', 'Manage profiles');
SELECT addTraduction('Gestion des relations', 'en_GB', 'Manage relationships');
SELECT addTraduction('Gestion des tables de paramétrage', 'en_GB', 'Manage the setup tables');
SELECT addTraduction('Gestion des utilisateurs', 'en_GB', 'Manage the users');
SELECT addTraduction('Gestion opérations div caisse/compte', 'en_GB', 'Manage miscellaneous cash/account operations');
SELECT addTraduction('Gestion opérations', 'en_GB', 'Manage operations');
SELECT addTraduction('Gestion plan comptable', 'en_GB', 'Manage accounting plan');
SELECT addTraduction('Guichet', 'en_GB', 'Counter');
SELECT addTraduction('Génération rapport', 'en_GB', 'Report generation');
SELECT addTraduction('Impression Suivi crédit', 'en_GB', 'Printing loan tracking');
SELECT addTraduction('Impression fiche client', 'en_GB', 'Printing a client file');
SELECT addTraduction('Impression proposition', 'en_GB', 'Printing proposal');
SELECT addTraduction('Impression rapport', 'en_GB', 'Printing report');
SELECT addTraduction('Impression échéancier', 'en_GB', 'Printing schedule');
SELECT addTraduction('Impression', 'en_GB', 'Printing');
SELECT addTraduction('Information', 'en_GB', 'Information');
SELECT addTraduction('Informations code utilisateur', 'en_GB', 'User code information');
SELECT addTraduction('Informations code', 'en_GB', 'Code information');
SELECT addTraduction('Informations d''arrêté', 'en_GB', 'Closing information');
SELECT addTraduction('Informations financières', 'en_GB', 'Financial information');
SELECT addTraduction('Informations personnelles', 'en_GB', 'Personal information');
SELECT addTraduction('Informations sur les comptes', 'en_GB', 'Accounts information');
SELECT addTraduction('Insertion', 'en_GB', 'Insertion');
SELECT addTraduction('Intitulé du compte', 'en_GB', 'Account holder');
SELECT addTraduction('Listes des messages SWIFT', 'en_GB', 'SWIFT message lists');
SELECT addTraduction('Menu Crédit', 'en_GB', 'Credit menu');
SELECT addTraduction('Menu Documents', 'en_GB', 'Documents menu');
SELECT addTraduction('Menu Epargne', 'en_GB', 'Savings menu');
SELECT addTraduction('Menu clientèle', 'en_GB', 'Clients menu');
SELECT addTraduction('Menu principal', 'en_GB', 'Main menu');
SELECT addTraduction('Mise en place dossier de crédit', 'en_GB', 'Establishing of a loan file');
SELECT addTraduction('Mobilisation des garanties', 'en_GB', 'Mobilizing securities');
SELECT addTraduction('Mode de déboursement', 'en_GB', 'Reimbursement method');
SELECT addTraduction('Mode de remboursement', 'en_GB', 'Reimbursement method');
SELECT addTraduction('Modification association profil', 'en_GB', 'Modify profile association');
SELECT addTraduction('Modification autre mot de passe', 'en_GB', 'Modify other password');
SELECT addTraduction('Modification client', 'en_GB', 'Modify client');
SELECT addTraduction('Modification code', 'en_GB', 'Modify code');
SELECT addTraduction('Modification d''une garantie', 'en_GB', 'Modify a security');
SELECT addTraduction('Modification de compte', 'en_GB', 'Modify account');
SELECT addTraduction('Modification de garantie', 'en_GB', 'Modify guarantee');
SELECT addTraduction('Modification de l''échéancier', 'en_GB', 'Modify schedule');
SELECT addTraduction('Modification de liason', 'en_GB', 'Modify reciprocal account');
SELECT addTraduction('Modification des journaux', 'en_GB', 'Modify journals');
SELECT addTraduction('Modification dossier de crédit', 'en_GB', 'Modify loan file');
SELECT addTraduction('Modification dossier', 'en_GB', 'Modify file');
SELECT addTraduction('Modification garantie', 'en_GB', 'Modify guarantee');
SELECT addTraduction('Modification message SWIFT', 'en_GB', 'Modify SWIFT message');
SELECT addTraduction('Modification mot de passe', 'en_GB', 'Modify password');
SELECT addTraduction('Modification opé auxiliaires', 'en_GB', 'Modify auxiliary operations');
SELECT addTraduction('Modification opération diverse', 'en_GB', 'Modify miscellaneous operation');
SELECT addTraduction('Modification opérations diverses', 'en_GB', 'Modify miscellaneous operations');
SELECT addTraduction('Modification profil', 'en_GB', 'Modify profile');
SELECT addTraduction('Modification utilisateur', 'en_GB', 'Modify user');
SELECT addTraduction('Modification', 'en_GB', 'Modification');
SELECT addTraduction('Nouveau', 'en_GB', 'New');
SELECT addTraduction('Opérations div de caisse/compte', 'en_GB', 'Misc cash/account operations');
SELECT addTraduction('Ordres Permanents', 'en_GB', 'Permanent orders');
SELECT addTraduction('Ouverture compte', 'en_GB', 'Account opening');
SELECT addTraduction('Ouverture', 'en_GB', 'Opening');
SELECT addTraduction('Paiement Net Bank', 'en_GB', 'Net Bank payment');
SELECT addTraduction('Paramétrage table', 'en_GB', 'Table setup');
SELECT addTraduction('Paramétrage', 'en_GB', 'Setup');
SELECT addTraduction('Passage d''écritures libres', 'en_GB', 'Posting of free entries');
SELECT addTraduction('Passage en perte', 'en_GB', 'Write-off');
SELECT addTraduction('Passage opérations siège/agence', 'en_GB', 'Posting of a head-office/agency operation');
SELECT addTraduction('Passage opératon', 'en_GB', 'Posting operation');
SELECT addTraduction('Passage écriture annulation', 'en_GB', 'Posting cancellation entry');
SELECT addTraduction('Perception Versement Initial', 'en_GB', 'Initial payment collection');
SELECT addTraduction('Perception des commissions', 'en_GB', 'Collection of commissions');
SELECT addTraduction('Perception frais adhésion', 'en_GB', 'Collection of subscription fees');
SELECT addTraduction('Perception frais dossier', 'en_GB', 'Collection of file fees');
SELECT addTraduction('Perception', 'en_GB', 'Collection');
SELECT addTraduction('Personalisation du rapport', 'en_GB', 'Customization of the report');
SELECT addTraduction('Personnalisation rapport', 'en_GB', 'Customization of the report');
SELECT addTraduction('Plan comptable', 'en_GB', 'Accounting plan');
SELECT addTraduction('Prolongation de DAT', 'en_GB', 'Term deposit extension');
SELECT addTraduction('Provision crédits ', 'en_GB', 'Provision for loans');
SELECT addTraduction('Quitter', 'en_GB', 'Quit');
SELECT addTraduction('Radiation crédit', 'en_GB', 'Loan write-off');
SELECT addTraduction('Raison de la défection', 'en_GB', 'Reason for the abandonment');
SELECT addTraduction('Rapport PDF', 'en_GB', 'PDF Report');
SELECT addTraduction('Rapports agence', 'en_GB', 'Agency reports');
SELECT addTraduction('Rapports client', 'en_GB', 'Client reports');
SELECT addTraduction('Rapports comptabilité', 'en_GB', 'Accounting reports');
SELECT addTraduction('Rapports crédit', 'en_GB', 'Loan reports');
SELECT addTraduction('Rapports épargne', 'en_GB', 'Savings reports');
SELECT addTraduction('Rapports', 'en_GB', 'Reports');
SELECT addTraduction('Recharge Ferlo par Versement', 'en_GB', 'Ferlo reload by payment');
SELECT addTraduction('Recharge Ferlo', 'en_GB', 'Ferlo reload');
SELECT addTraduction('Recouvrement crédit en perte', 'en_GB', 'Recovery of loans showing a loss');
SELECT addTraduction('Rejet d''un dossier de crédit', 'en_GB', 'Rejection of a loan file');
SELECT addTraduction('Rejet dossier de crédit', 'en_GB', 'Rejection of loan file');
SELECT addTraduction('Rejet', 'en_GB', 'Reject');
SELECT addTraduction('Remboursement crédit', 'en_GB', 'Reimbursement of loan');
SELECT addTraduction('Rembousements à annuler', 'en_GB', 'Reimbursements to cancel');
SELECT addTraduction('Retrait chèquier', 'en_GB', 'Withdrawal from check book');
SELECT addTraduction('Retrait express', 'en_GB', 'Express withdrawal');
SELECT addTraduction('Retrait', 'en_GB', 'Withdrawal');
SELECT addTraduction('Réalisation de la garantie', 'en_GB', 'Enforce the security');
SELECT addTraduction('Réalisation garanties', 'en_GB', 'Enforcement of securities');
SELECT addTraduction('Résultat', 'en_GB', 'Result');
SELECT addTraduction('Rééch./Moratoire', 'en_GB', 'Rescheduled/Moratorium');
SELECT addTraduction('Rééchelonnement crédit', 'en_GB', 'Credit rescheduling');
SELECT addTraduction('Saisie Information', 'en_GB', 'Data entry');
SELECT addTraduction('Saisie code utilisateur', 'en_GB', 'User code entry');
SELECT addTraduction('Saisie critères', 'en_GB', 'Criteria entry');
SELECT addTraduction('Saisie des informations', 'en_GB', 'Data entry of information');
SELECT addTraduction('Saisie données', 'en_GB', 'Data entry');
SELECT addTraduction('Saisie détails', 'en_GB', 'Detailed data entry');
SELECT addTraduction('Saisie encaisse', 'en_GB', 'Cash balance entry');
SELECT addTraduction('Saisie information', 'en_GB', 'Data entry of information');
SELECT addTraduction('Saisie informations compte', 'en_GB', 'Account information entry');
SELECT addTraduction('Saisie informations', 'en_GB', 'Data entry information');
SELECT addTraduction('Saisie modification', 'en_GB', 'Modification data entry');
SELECT addTraduction('Saisie modifications', 'en_GB', 'Modification entry');
SELECT addTraduction('Saisie montant', 'en_GB', 'Amount entry');
SELECT addTraduction('Saisie opération diverse', 'en_GB', 'Miscellaneous operation entry');
SELECT addTraduction('Saisie opération', 'en_GB', 'Operation entry');
SELECT addTraduction('Saisie opératon', 'en_GB', 'Operation entry');
SELECT addTraduction('Saisie profil', 'en_GB', 'Profile entry');
SELECT addTraduction('Saisie proposition', 'en_GB', 'Proposal entry');
SELECT addTraduction('Saisie statut juridique', 'en_GB', 'Legal status entry');
SELECT addTraduction('Saisie écriture annulation', 'en_GB', 'Cancellation entry');
SELECT addTraduction('Saisie', 'en_GB', 'Data entry');
SELECT addTraduction('Sauvegarde données', 'en_GB', 'Data backup');
SELECT addTraduction('Selection client', 'en_GB', 'Selecting the client');
SELECT addTraduction('Selection de la garantie', 'en_GB', 'Selecting the security');
SELECT addTraduction('Selection dossier de crédit', 'en_GB', 'Selecting the loan file');
SELECT addTraduction('Selection du crédit', 'en_GB', 'Selecting the credit ');
SELECT addTraduction('Simulation arrêté compte', 'en_GB', 'Account closing simulation');
SELECT addTraduction('Simulation défection', 'en_GB', 'Abandonment simulation');
SELECT addTraduction('Simulation échéancier', 'en_GB', 'Schedule simulation');
SELECT addTraduction('Situation analytique client', 'en_GB', 'Analytical client situation');
SELECT addTraduction('Situation finale', 'en_GB', 'Final situation');
SELECT addTraduction('Situation globale client', 'en_GB', 'Global situation of client');
SELECT addTraduction('Solde des comptes', 'en_GB', 'Accounts balance');
SELECT addTraduction('Souscription parts sociales par lot ', 'en_GB', 'Batch purchase of shares');
SELECT addTraduction('Souscription parts sociales', 'en_GB', 'Purchase of shares');
SELECT addTraduction('Suivi du crédit', 'en_GB', 'Loan tracking');
SELECT addTraduction('Suppression code', 'en_GB', 'Delete code');
SELECT addTraduction('Suppression contrepartie', 'en_GB', 'Delete offset');
SELECT addTraduction('Suppression d''une garantie', 'en_GB', 'Delete a security');
SELECT addTraduction('Suppression de garantie', 'en_GB', 'Delete guarantee');
SELECT addTraduction('Suppression des journaux', 'en_GB', 'Delete journals');
SELECT addTraduction('Suppression dossier', 'en_GB', 'Delete file');
SELECT addTraduction('Suppression garantie', 'en_GB', 'Delete guarantee');
SELECT addTraduction('Suppression opération diverse', 'en_GB', 'Delete miscellaneous operation');
SELECT addTraduction('Suppression profil', 'en_GB', 'Delete profile');
SELECT addTraduction('Suppression utilisateur', 'en_GB', 'Delete user');
SELECT addTraduction('Suppression', 'en_GB', 'Deletion');
SELECT addTraduction('Suppressions de liaison', 'en_GB', 'Delete reciprocal accounts');
SELECT addTraduction('Susp / ajust pénalités', 'en_GB', 'Suspension / adjustment penalties');
SELECT addTraduction('Système', 'en_GB', 'System');
SELECT addTraduction('Sélection Dossier de crédit', 'en_GB', 'Selecting the loan file');
SELECT addTraduction('Sélection chèquier', 'en_GB', 'Selecting check book');
SELECT addTraduction('Sélection compte', 'en_GB', 'Selecting the account');
SELECT addTraduction('Sélection contenu', 'en_GB', 'Selecting content');
SELECT addTraduction('Sélection de la période', 'en_GB', 'Selecting the period');
SELECT addTraduction('Sélection données agence', 'en_GB', 'Selecting agency data');
SELECT addTraduction('Sélection dossier crédit', 'en_GB', 'Selecting the credit file');
SELECT addTraduction('Sélection dossier de crédit', 'en_GB', 'Selecting the loan file');
SELECT addTraduction('Sélection dossier', 'en_GB', 'Selecting file');
SELECT addTraduction('Sélection entrée', 'en_GB', 'Selecting entry');
SELECT addTraduction('Sélection ordre permanent', 'en_GB', 'Selecting permanent order');
SELECT addTraduction('Sélection table', 'en_GB', 'Selecting table');
SELECT addTraduction('Sélection type de sauvegarde', 'en_GB', 'Selecting the backup type');
SELECT addTraduction('Sélection type', 'en_GB', 'Selecting type');
SELECT addTraduction('Traitement clôture', 'en_GB', 'Processing closing');
SELECT addTraduction('Traitement des attentes de crédit', 'en_GB', 'Processing credit holds');
SELECT addTraduction('Traitement des journaux', 'en_GB', 'Processing journals');
SELECT addTraduction('Traitement des message SWIFT', 'en_GB', 'Processing SWIFT messages');
SELECT addTraduction('Traitement des transactions Ferlo', 'en_GB', 'Processing of FERLO transactions');
SELECT addTraduction('Traitement fin journée', 'en_GB', 'Processing day closing');
SELECT addTraduction('Traitement', 'en_GB', 'Processing');
SELECT addTraduction('Transfert des assurances', 'en_GB', 'Transfer of insurances');
SELECT addTraduction('Transfert des fonds du crédit', 'en_GB', 'Transfer of loan funds');
SELECT addTraduction('Transfert des garanties', 'en_GB', 'Transfer of guarantees');
SELECT addTraduction('Transfert', 'en_GB', 'Transfer');
SELECT addTraduction('Type de correction', 'en_GB', 'Type of correction');
SELECT addTraduction('Validation', 'en_GB', 'Validation');
SELECT addTraduction('Versement sur compte', 'en_GB', 'Payment on account');
SELECT addTraduction('Visualisation dernier rapport', 'en_GB', 'View latest report');
SELECT addTraduction('Visualisation exercice', 'en_GB', 'View fiscal year');
SELECT addTraduction('Visualisation jours ouvrables', 'en_GB', 'View working days');
SELECT addTraduction('Visualisation toutes transactions', 'en_GB', 'View all transactions');
SELECT addTraduction('Visualisation transactions', 'en_GB', 'View transactions');
SELECT addTraduction('Visualisation', 'en_GB', 'View');
SELECT addTraduction('Ajout taxe', 'en_GB', 'Add tax');
SELECT addTraduction('Suppression taxe', 'en_GB', 'Delete tax');
SELECT addTraduction('Rapports externe', 'en_GB', 'External reports');

-- tableliste.sql in en_GB
SELECT addTraduction('Abréviation', 'en_GB', 'Abbreviation');
SELECT addTraduction('Activité professionnelle', 'en_GB', 'Professional activity');
SELECT addTraduction('Adresse email', 'en_GB', 'E-mail address');
SELECT addTraduction('Adresse réseau', 'en_GB', 'Network address');
SELECT addTraduction('Adresse', 'en_GB', 'Address');
SELECT addTraduction('Afficher l''arborescence dans la fenêtre gauche ?', 'en_GB', 'Display the tree structure in the left window?');
SELECT addTraduction('Affiliation réseau', 'en_GB', 'Network affiliation');
SELECT addTraduction('Agent gestionnaire', 'en_GB', 'Service agent');
SELECT addTraduction('Ancien N° Client', 'en_GB', 'Former Client Number');
SELECT addTraduction('Annee', 'en_GB', 'Year');
SELECT addTraduction('Annulation automatique du découvert', 'en_GB', 'Automatic overdraft cancellation');
SELECT addTraduction('Années', 'en_GB', 'Years');
SELECT addTraduction('Appartenance à un groupe informel', 'en_GB', 'Membership in an informal group');
SELECT addTraduction('Appliquer la commission sur la devise de réf ?', 'en_GB', 'Apply the commission on the reporting currency?');
SELECT addTraduction('Appliquer le calcul des intérêts sur les échéances diffèrées', 'en_GB', 'Apply the interests calculated on deferred terms');
SELECT addTraduction('Appliquer le différé sur l''épargne nantie', 'en_GB', 'Apply the deferral on the guaranteed savings');
SELECT addTraduction('Appliquer le taux, la fréquence et le mode de calcul sur les comptes existants ?', 'en_GB', 'Apply the rate');
SELECT addTraduction('Approbation obligatoire', 'en_GB', 'Approval required');
SELECT addTraduction('Association des comptes aux opérations', 'en_GB', 'Association of accounts with the operations');
SELECT addTraduction('Assurance a joué ?', 'en_GB', 'The insurance came into effect?');
SELECT addTraduction('Attente des mouvements avec l''extérieur', 'en_GB', 'Waiting for transactions with the outside');
SELECT addTraduction('Autorité ayant délivré l''acte d''agrément', 'en_GB', 'Authority that delivered the act of accreditation');
SELECT addTraduction('Banque', 'en_GB', 'Bank');
SELECT addTraduction('Base de calcul du taux d''intérêt pour l''épargne', 'en_GB', 'Notional amount for the interest rate for savings');
SELECT addTraduction('Base de calcul du taux d''intérêt pour le crédit', 'en_GB', 'Notional amount of lending rate');
SELECT addTraduction('Bases utilisées pour le calcul des taux d''inrérêt', 'en_GB', 'Notional amounts for interest rates');
SELECT addTraduction('Billettage requis ?', 'en_GB', 'Banknote required?');
SELECT addTraduction('Brouillard des opérations', 'en_GB', 'Operations blotter');
SELECT addTraduction('Bénéficiaire extérieur', 'en_GB', 'External beneficiary');
SELECT addTraduction('Bénéficiaire', 'en_GB', 'Beneficiary');
SELECT addTraduction('Calcul automatique provision crédits en souffrances ?', 'en_GB', 'Automatic calculation of delinquent credit provision?');
SELECT addTraduction('Casier judiciaire?', 'en_GB', 'Police record?');
SELECT addTraduction('Categorie compte', 'en_GB', 'Account category');
SELECT addTraduction('Categorie du compte', 'en_GB', 'Account category');
SELECT addTraduction('Catégorie de PM', 'en_GB', 'PM Category');
SELECT addTraduction('Catégorie de groupe solidaire', 'en_GB', 'Solidarity group category');
SELECT addTraduction('Catégorie opération', 'en_GB', 'Operation category');
SELECT addTraduction('Chèques', 'en_GB', 'Checks');
SELECT addTraduction('Classe comptable', 'en_GB', 'Accounting class');
SELECT addTraduction('Clients', 'en_GB', 'Clients');
SELECT addTraduction('Clôtures périodiques automatiques', 'en_GB', 'Automatic period closings');
SELECT addTraduction('Code ISO de la devise', 'en_GB', 'ISO Code of the Currency');
SELECT addTraduction('Code ISO du pays', 'en_GB', 'ISO code of the country');
SELECT addTraduction('Code Postal', 'en_GB', 'Postal Code');
SELECT addTraduction('Code SWIFT de la banque', 'en_GB', 'SWIFT code of the bank');
SELECT addTraduction('Code SWIFT', 'en_GB', 'SWIFT Code');
SELECT addTraduction('Code de l''antenne', 'en_GB', 'Antenna code');
SELECT addTraduction('Code de la banque', 'en_GB', 'Bank code');
SELECT addTraduction('Code de la ville', 'en_GB', 'City code');
SELECT addTraduction('Code du journal (3 caractères)', 'en_GB', 'Journal code (3 characters)');
SELECT addTraduction('Code institution', 'en_GB', 'Institution code');
SELECT addTraduction('Code langue', 'en_GB', 'Language code');
SELECT addTraduction('Code postal', 'en_GB', 'Postal Code');
SELECT addTraduction('Code utilisateur', 'en_GB', 'User code');
SELECT addTraduction('Codes utilisateurs (logins)', 'en_GB', 'User codes (logins)');
SELECT addTraduction('Commission de change minimale', 'en_GB', 'Minimum exchange commission');
SELECT addTraduction('Communication vers l''extérieur', 'en_GB', 'Outwards communication ');
SELECT addTraduction('Communication', 'en_GB', 'Communication');
SELECT addTraduction('Compartiment comptable', 'en_GB', 'Accounting compartment');
SELECT addTraduction('Compartiments comptables', 'en_GB', 'Accounting compartments');
SELECT addTraduction('Compte associé à l''état de credit', 'en_GB', 'Account associated to the state of the credit');
SELECT addTraduction('Compte centralisateur', 'en_GB', 'Concentrator account');
SELECT addTraduction('Compte coffre-fort', 'en_GB', 'Safety deposit box account');
SELECT addTraduction('Compte comptable associé', 'en_GB', 'Associated accounting account');
SELECT addTraduction('Compte comptable des garanties', 'en_GB', 'Guarantee accounting account');
SELECT addTraduction('Compte comptable des intérêts', 'en_GB', 'Interests accounting account');
SELECT addTraduction('Compte comptable des penalités', 'en_GB', 'Penalties accounting account');
SELECT addTraduction('Compte comptable', 'en_GB', 'Accounting account');
SELECT addTraduction('Compte correspondant', 'en_GB', 'Contra account');
SELECT addTraduction('Compte d''attente variation taux créditeur', 'en_GB', 'Suspense account for credit rate variation');
SELECT addTraduction('Compte d''attente variation taux débiteur', 'en_GB', 'Suspense account for debit rate variation');
SELECT addTraduction('Compte d''ordre créditeur', 'en_GB', 'Credit suspense account');
SELECT addTraduction('Compte d''ordre débiteur', 'en_GB', 'Debit suspense account');
SELECT addTraduction('Compte de contre partie', 'en_GB', 'Offset account');
SELECT addTraduction('Compte de contrevaleur position de change', 'en_GB', 'Exchange position counterpart account');
SELECT addTraduction('Compte de crédit', 'en_GB', 'Credit account');
SELECT addTraduction('Compte de garantie', 'en_GB', 'Guarantee account');
SELECT addTraduction('Compte de provision', 'en_GB', 'Provision account');
SELECT addTraduction('Compte de prélèvement', 'en_GB', 'Drawing account');
SELECT addTraduction('Compte de versement des intérêts', 'en_GB', 'Interest payment account');
SELECT addTraduction('Compte de virement à la clôture', 'en_GB', 'Transfer account at closing');
SELECT addTraduction('Compte des Traveller''s Chèque', 'en_GB', 'Traveler''s Check account');
SELECT addTraduction('Compte des garanties numéraires à constituer en cours', 'en_GB', 'Cash securities account in process');
SELECT addTraduction('Compte des positions de change', 'en_GB', 'Exchange position account');
SELECT addTraduction('Compte destinataire', 'en_GB', 'Destination account');
SELECT addTraduction('Compte du bénéficiaire', 'en_GB', 'Beneficiary account');
SELECT addTraduction('Compte du donneur d''ordre', 'en_GB', 'Originator account');
SELECT addTraduction('Compte hors bilan ', 'en_GB', 'Off-balance sheet account ');
SELECT addTraduction('Compte lié', 'en_GB', 'Linked account');
SELECT addTraduction('Compte', 'en_GB', 'Account');
SELECT addTraduction('Comptes', 'en_GB', 'Accounts');
SELECT addTraduction('Constante de la commission de change', 'en_GB', 'Exchange commission percentage');
SELECT addTraduction('Correspondant', 'en_GB', 'Correspondent');
SELECT addTraduction('Cumul des intérêts sur année en cours', 'en_GB', 'Interest accumulation for the current year');
SELECT addTraduction('DAT prolongé?', 'en_GB', 'DAT extended?');
SELECT addTraduction('Date ', 'en_GB', 'Date ');
SELECT addTraduction('Date comptable', 'en_GB', 'Accounting date');
SELECT addTraduction('Date d''adhésion', 'en_GB', 'Subscription date');
SELECT addTraduction('Date d''agrément du groupe informel', 'en_GB', 'Approval date of the informal group');
SELECT addTraduction('Date d''agrément/convention', 'en_GB', 'Approval date / agreement');
SELECT addTraduction('Date d''approbation', 'en_GB', 'Approval date');
SELECT addTraduction('Date d''expiration de la pièce d''identité', 'en_GB', 'Expiry date of identity document');
SELECT addTraduction('Date d''expiration de pièce d''identité', 'en_GB', 'Expiry date of identity document');
SELECT addTraduction('Date d''expiration', 'en_GB', 'Expiry date');
SELECT addTraduction('Date d''ouverture', 'en_GB', 'Date opened');
SELECT addTraduction('Date de blocage', 'en_GB', 'Date blocked');
SELECT addTraduction('Date de clôture', 'en_GB', 'Closing date');
SELECT addTraduction('Date de commande du chéquier', 'en_GB', 'Check book order date');
SELECT addTraduction('Date de constitution', 'en_GB', 'Date of incorporation');
SELECT addTraduction('Date de création', 'en_GB', 'Creation date');
SELECT addTraduction('Date de demande', 'en_GB', 'Request date');
SELECT addTraduction('Date de dernière ouverture', 'en_GB', 'Date of last opening');
SELECT addTraduction('Date de dissolution du groupe informel', 'en_GB', 'Dissolution date of the informal group');
SELECT addTraduction('Date de déblocage', 'en_GB', 'Date for unblocking');
SELECT addTraduction('Date de défection', 'en_GB', 'Date of abandonment');
SELECT addTraduction('Date de délivrance de la pièce d''identité', 'en_GB', 'Date of delivery of identity document');
SELECT addTraduction('Date de dépôt du chèque', 'en_GB', 'Check deposit date');
SELECT addTraduction('Date de fin cycle (épargne à la source)', 'en_GB', 'End of cycle date (savings at the source)');
SELECT addTraduction('Date de fin du compte à terme', 'en_GB', 'End date of the term account');
SELECT addTraduction('Date de l''acte d''agrément', 'en_GB', 'Date of act of accreditation');
SELECT addTraduction('Date de l''état du crédit', 'en_GB', 'File status date');
SELECT addTraduction('Date de la pièce', 'en_GB', 'Date of document');
SELECT addTraduction('Date de modification de l''état du dossier', 'en_GB', 'File status modification date');
SELECT addTraduction('Date de modification', 'en_GB', 'Modification date');
SELECT addTraduction('Date de naissance de la relation', 'en_GB', 'Birth date of the relationship');
SELECT addTraduction('Date de naissance', 'en_GB', 'Birth date');
SELECT addTraduction('Date de pièce d''identité', 'en_GB', 'Identity document date');
SELECT addTraduction('Date de première utilisation du découvert', 'en_GB', 'Date of first overdraft use');
SELECT addTraduction('Date de rupture', 'en_GB', 'Breach date');
SELECT addTraduction('Date decision prolongation compte à terme', 'en_GB', 'Date of decision of extension of term account');
SELECT addTraduction('Date du chèque', 'en_GB', 'Check date');
SELECT addTraduction('Date du log', 'en_GB', 'Log date');
SELECT addTraduction('Date début', 'en_GB', 'Start date');
SELECT addTraduction('Date dépôt greffe', 'en_GB', 'Filing date in Registry');
SELECT addTraduction('Date encaisse', 'en_GB', 'Date of fund entry');
SELECT addTraduction('Date encodage', 'en_GB', 'Date of encoding');
SELECT addTraduction('Date fin', 'en_GB', 'End date');
SELECT addTraduction('Date modification', 'en_GB', 'Modification date');
SELECT addTraduction('Date notaire', 'en_GB', 'Notary date');
SELECT addTraduction('Date ouverture', 'en_GB', 'Opening date');
SELECT addTraduction('Date remboursement', 'en_GB', 'Date of reimbursement');
SELECT addTraduction('Date solde calcul interets', 'en_GB', 'Interest calculation balance date');
SELECT addTraduction('Date échéance', 'en_GB', 'Due date');
SELECT addTraduction('Delai de grâce', 'en_GB', 'Grace period');
SELECT addTraduction('Denomination', 'en_GB', 'Denomination');
SELECT addTraduction('Depasse plafond depot guichet?', 'en_GB', 'Exceeds counter deposit ceiling?');
SELECT addTraduction('Depasse plafond retrait guichet?', 'en_GB', 'Exceeds counter withdrawal ceiling?');
SELECT addTraduction('Description du bien', 'en_GB', 'Property description');
SELECT addTraduction('Destination du reste', 'en_GB', 'Destination of balance');
SELECT addTraduction('Devise de référence', 'en_GB', 'Reference currency');
SELECT addTraduction('Devise de vente', 'en_GB', 'Selling currency');
SELECT addTraduction('Devise du compte', 'en_GB', 'Account currency');
SELECT addTraduction('Devise du crédit', 'en_GB', 'Loan currency');
SELECT addTraduction('Devise', 'en_GB', 'Currency');
SELECT addTraduction('Devises', 'en_GB', 'Currencies');
SELECT addTraduction('Différé en jours', 'en_GB', 'Deferral in days');
SELECT addTraduction('Différé en échéances', 'en_GB', 'Deferral of amounts due');
SELECT addTraduction('Différé maximum en jours', 'en_GB', 'Maximum deferral in days');
SELECT addTraduction('Différé maximum en échéances', 'en_GB', 'Maximum deferral of amounts due');
SELECT addTraduction('Donneur d''ordre extérieur', 'en_GB', 'External originator');
SELECT addTraduction('Dossier fictifs membres groupe solidaidre', 'en_GB', 'Dummy file folders of members of solidarity group');
SELECT addTraduction('Dossiers de crédit', 'en_GB', 'Credit files');
SELECT addTraduction('Durée du crédit', 'en_GB', 'Loan duration');
SELECT addTraduction('Durée maximum (0 si aucun)', 'en_GB', 'Maximum duration (0 if none)');
SELECT addTraduction('Durée minimum avant octroi crédit (mois)', 'en_GB', 'Minimum duration before loan granting (months)');
SELECT addTraduction('Durée minimum avant octroi crédit (mois)', 'en_GB', 'Minimum duration before loan granting (months)');
SELECT addTraduction('Durée minimum entre deux retraits (en jours, 0 si aucun)', 'en_GB', 'Minimum duration between two withdrawals (in days)');
SELECT addTraduction('Durée minimum', 'en_GB', 'Minimum duration');
SELECT addTraduction('Décision de prolonger le compte à terme', 'en_GB', 'Extending the term account decision');
SELECT addTraduction('Découvert autorisé', 'en_GB', 'Authorized overdraft');
SELECT addTraduction('Délai de déclenchement de l''alerte compte à terme (jours)', 'en_GB', 'Timeline alert for term account (days)');
SELECT addTraduction('Délai de grâce en jour', 'en_GB', 'Grace period in days');
SELECT addTraduction('Délai max. perception frais d''adhésion(jours)', 'en_GB', 'Maximum time period for subscription fees collection (days)');
SELECT addTraduction('Dénomination', 'en_GB', 'Denomination');
SELECT addTraduction('Dépôt unique ?', 'en_GB', 'Unique deposit?');
SELECT addTraduction('Détail des opérations comptables', 'en_GB', 'Accounting operations details');
SELECT addTraduction('Détail objet de la demande', 'en_GB', 'Detail object of the request');
SELECT addTraduction('Détail', 'en_GB', 'Detail');
SELECT addTraduction('Détails du motif', 'en_GB', 'Motive details');
SELECT addTraduction('E-mail 2', 'en_GB', 'E-mail 2');
SELECT addTraduction('E-mail', 'en_GB', 'E-mail');
SELECT addTraduction('Echéancier théorique', 'en_GB', 'Notional schedule');
SELECT addTraduction('Encaissé ?', 'en_GB', 'Cashed in?');
SELECT addTraduction('Est compte principal d''un journal', 'en_GB', 'Is a principal journal account');
SELECT addTraduction('Etat civil', 'en_GB', 'Civil status');
SELECT addTraduction('Etat commande de chéquier', 'en_GB', 'Check book order status');
SELECT addTraduction('Etat d''un compte d''épargne', 'en_GB', 'Savings account status');
SELECT addTraduction('Etat d''un crédit', 'en_GB', 'Loan status');
SELECT addTraduction('Etat de l''attente de crédit', 'en_GB', 'Credit hold status');
SELECT addTraduction('Etat de l''attente du crédit', 'en_GB', 'Credit hold status');
SELECT addTraduction('Etat de la garantie', 'en_GB', 'Status of the security');
SELECT addTraduction('Etat du client', 'en_GB', 'Client status');
SELECT addTraduction('Etat du compte', 'en_GB', 'Account status');
SELECT addTraduction('Etat du crédit', 'en_GB', 'Loan status');
SELECT addTraduction('Etat du dossier', 'en_GB', 'File status');
SELECT addTraduction('Etat du journal', 'en_GB', 'Journal status');
SELECT addTraduction('Etat du transfert', 'en_GB', 'Transfer status');
SELECT addTraduction('Etat le plus avancé', 'en_GB', 'Most advanced status');
SELECT addTraduction('Etat', 'en_GB', 'Status');
SELECT addTraduction('Etats d''un dossier de crédit', 'en_GB', 'Loan file status');
SELECT addTraduction('Etats exercice', 'en_GB', 'Fiscal year status');
SELECT addTraduction('Exercice courant', 'en_GB', 'Current fiscal year');
SELECT addTraduction('Exercices comptables', 'en_GB', 'Fiscal years');
SELECT addTraduction('Existence d''un certificat ?', 'en_GB', 'Does a certificate exist?');
SELECT addTraduction('Fax', 'en_GB', 'Fax');
SELECT addTraduction('Fonction de l''employé', 'en_GB', 'Employee position');
SELECT addTraduction('Fonction', 'en_GB', 'Function');
SELECT addTraduction('Fonctions systèmes', 'en_GB', 'System functions');
SELECT addTraduction('Frais de commande d''un chequier', 'en_GB', 'Fee to order a check book');
SELECT addTraduction('Frais de dossier de découvert (à l''octroi)', 'en_GB', 'Account overdraft fee rate (when granted)');
SELECT addTraduction('Frais de dossier de découvert en pourcentage', 'en_GB', 'Account overdraft fee in percentage');
SELECT addTraduction('Frais de découvert à l''utilisation', 'en_GB', 'Account overdraft fee rate');
SELECT addTraduction('Frais de dépôt', 'en_GB', 'Deposit fee');
SELECT addTraduction('Frais de fermeture de compte', 'en_GB', 'Fee for closing an account');
SELECT addTraduction('Frais de rejet encaissés ?', 'en_GB', 'Cash rejection fee received?');
SELECT addTraduction('Frais de retrait', 'en_GB', 'Withdrawal fee');
SELECT addTraduction('Frais de tenue du compte', 'en_GB', 'Account managing fee');
SELECT addTraduction('Frais de transfert entre comptes', 'en_GB', 'Fees for transfer between accounts');
SELECT addTraduction('Frais ouverture', 'en_GB', 'Opening fees');
SELECT addTraduction('Frequence de calcul', 'en_GB', 'Calculation frequency');
SELECT addTraduction('Fréquence clôture périodique', 'en_GB', 'Periodic closure frequency');
SELECT addTraduction('Fréquence de calcul des interêts', 'en_GB', 'Interest calculation frequency');
SELECT addTraduction('Fréquence de paiement du capital (en échéances)', 'en_GB', 'Frequency of payment of capital (as and when due)');
SELECT addTraduction('Fréquence perception des frais de tenue de compte', 'en_GB', 'Frequency of collection of the managing account fees');
SELECT addTraduction('Garantie matérielle à bloquer au début ', 'en_GB', 'Material security to block at the beginning');
SELECT addTraduction('Garantie numéraire à bloquer au début ', 'en_GB', 'Cash security to block at the beginning');
SELECT addTraduction('Garantie totale à bloquer au début ', 'en_GB', 'Total security to block at the beginning');
SELECT addTraduction('Garantie totale', 'en_GB', 'Total security');
SELECT addTraduction('Garanties matérielles à bloquer au début', 'en_GB', 'Material securities to block at the beginning');
SELECT addTraduction('Garanties numéraires à bloquer au début ', 'en_GB', 'Cash securities to block at the beginning');
SELECT addTraduction('Garanties numéraires à constituer en cours', 'en_GB', 'Cash securities in process');
SELECT addTraduction('Gatégorie dossier de groupe', 'en_GB', 'Group file category');
SELECT addTraduction('Gestionnaire', 'en_GB', 'Manager');
SELECT addTraduction('Guichet', 'en_GB', 'Counter');
SELECT addTraduction('Historique des échanges extérieurs', 'en_GB', 'History of external exchanges');
SELECT addTraduction('Historique', 'en_GB', 'History');
SELECT addTraduction('ID Agence', 'en_GB', 'Agency ID');
SELECT addTraduction('ID classe comptable', 'en_GB', 'Accounting class ID');
SELECT addTraduction('ID client', 'en_GB', 'Client ID');
SELECT addTraduction('ID compte', 'en_GB', 'Account ID');
SELECT addTraduction('ID de l''attente de crédit', 'en_GB', 'Credit hold ID');
SELECT addTraduction('ID de l''état précédent', 'en_GB', 'Previous status ID');
SELECT addTraduction('ID de la base', 'en_GB', 'Base ID');
SELECT addTraduction('ID de la fréquence', 'en_GB', 'Frequency ID');
SELECT addTraduction('ID de transaction', 'en_GB', 'Transaction ID');
SELECT addTraduction('ID du mouvement', 'en_GB', 'Transaction ID');
SELECT addTraduction('ID du pays', 'en_GB', 'Country ID');
SELECT addTraduction('ID du statut du transfert étranger', 'en_GB', 'Status of foreign transfer ID');
SELECT addTraduction('ID du terme d''un crédit', 'en_GB', 'Loan term ID');
SELECT addTraduction('ID du type de pièce comptable', 'en_GB', 'Accounting document type label ID');
SELECT addTraduction('ID mandat', 'en_GB', 'Mandate ID');
SELECT addTraduction('ID operation', 'en_GB', 'Operation ID');
SELECT addTraduction('ID opération', 'en_GB', 'Operation ID');
SELECT addTraduction('ID personne extérieure', 'en_GB', 'External person ID');
SELECT addTraduction('ID titulaire', 'en_GB', 'Holder ID');
SELECT addTraduction('ID utilisateur créateur', 'en_GB', 'Creator user ID');
SELECT addTraduction('ID', 'en_GB', 'ID');
SELECT addTraduction('Id dossier du groupe', 'en_GB', 'Group file ID');
SELECT addTraduction('Id du calcul des provisions', 'en_GB', 'Provisions calculation ID');
SELECT addTraduction('Id du journal', 'en_GB', 'Journal ID');
SELECT addTraduction('Identifiant de la Banque', 'en_GB', 'Bank identifier');
SELECT addTraduction('Identifiant de la garantie', 'en_GB', 'Guarantee identifier');
SELECT addTraduction('Identifiant dossier groupe', 'en_GB', 'Group file identifier');
SELECT addTraduction('Identifiant du bien', 'en_GB', 'Property identifier');
SELECT addTraduction('Identifiant du dossier fictif', 'en_GB', 'Dummy file folder identifier');
SELECT addTraduction('Identifiant du membre', 'en_GB', 'Member identifier');
SELECT addTraduction('Identifiant du type de bien', 'en_GB', 'Property type identifier');
SELECT addTraduction('Identifiant', 'en_GB', 'Identifier');
SELECT addTraduction('Identificateur de la banque émettrice', 'en_GB', 'Originating bank identifier');
SELECT addTraduction('Identificateur', 'en_GB', 'Identifier');
SELECT addTraduction('Imprimer Coordonnées et réfèrences', 'en_GB', 'Print contact and reference data');
SELECT addTraduction('Informations complémentaires', 'en_GB', 'Extra information');
SELECT addTraduction('Informations sur l''employeur', 'en_GB', 'Employer information');
SELECT addTraduction('Intitulé du compte', 'en_GB', 'Account holder');
SELECT addTraduction('Jour de la semaine', 'en_GB', 'Day of week');
SELECT addTraduction('Jour du mois', 'en_GB', 'Day of month');
SELECT addTraduction('Journaux comptables', 'en_GB', 'Accounting journals');
SELECT addTraduction('Jours de la semaine', 'en_GB', 'Days of week');
SELECT addTraduction('Jours du mois', 'en_GB', 'Days of month');
SELECT addTraduction('Jours feriés', 'en_GB', 'Legal holidays');
SELECT addTraduction('Langue de correspondance', 'en_GB', 'Correspondence language');
SELECT addTraduction('Langue utilisateur', 'en_GB', 'User language');
SELECT addTraduction('Langue', 'en_GB', 'Language');
SELECT addTraduction('Langues du système', 'en_GB', 'System languages');
SELECT addTraduction('Langues', 'en_GB', 'Languages');
SELECT addTraduction('Les états des garanties', 'en_GB', 'Statuses of securities');
SELECT addTraduction('Libelle de Type opération', 'en_GB', 'Operation type label');
SELECT addTraduction('Libellé Etat civil', 'en_GB', 'Civil status label');
SELECT addTraduction('Libellé Etat crédit', 'en_GB', 'Loan status label');
SELECT addTraduction('Libellé Etat d''un compte d''épargne', 'en_GB', 'Savings account status label');
SELECT addTraduction('Libellé Etat d''une garantie', 'en_GB', 'Guarantee status label');
SELECT addTraduction('Libellé Etat du client', 'en_GB', 'Client status label');
SELECT addTraduction('Libellé Fonctions systèmes', 'en_GB', 'System functions label');
SELECT addTraduction('Libellé Mode de calcul des garanties', 'en_GB', 'Guarantee calculation method label');
SELECT addTraduction('Libellé Mode de calcul des intérêts sur le crédit', 'en_GB', 'Loan interest calculation method label');
SELECT addTraduction('Libellé Mode de calcul des pénalités', 'en_GB', 'Penalties calculation method label');
SELECT addTraduction('Libellé Qualité Client', 'en_GB', 'Client quality label');
SELECT addTraduction('Libellé Statut juridique', 'en_GB', 'Legal status label');
SELECT addTraduction('Libellé Types d''opérations (Table hist)', 'en_GB', 'Operations types label (Hist. Table)');
SELECT addTraduction('Libellé Types de garanties', 'en_GB', 'Security types label');
SELECT addTraduction('Libellé Types de relations', 'en_GB', 'Relationships types label');
SELECT addTraduction('Libellé classe comptable', 'en_GB', 'Accounting class label');
SELECT addTraduction('Libellé d''Etats d''un dossier de crédit', 'en_GB', 'Loan file status label');
SELECT addTraduction('Libellé de l''institution', 'en_GB', 'Institution label');
SELECT addTraduction('Libellé de l''état de l''exercice', 'en_GB', 'Fiscal year status label');
SELECT addTraduction('Libellé de l''état du compte', 'en_GB', 'Account status label');
SELECT addTraduction('Libellé de l''état du journal', 'en_GB', 'Journal status label');
SELECT addTraduction('Libellé de la base', 'en_GB', 'Base label');
SELECT addTraduction('Libellé de la categorie du compte', 'en_GB', 'Account category label');
SELECT addTraduction('Libellé de la devise', 'en_GB', 'Currency label');
SELECT addTraduction('Libellé de la fréquence', 'en_GB', 'Frequency label');
SELECT addTraduction('Libellé du Type de calcul de provision', 'en_GB', 'Provision calculation type label');
SELECT addTraduction('Libellé du Type de périodicité de remboursement', 'en_GB', 'Reimbursement periodicity type label');
SELECT addTraduction('Libellé du calcul des provisions', 'en_GB', 'Provisions calculation label');
SELECT addTraduction('Libellé du compte comptable', 'en_GB', 'Accounting account label');
SELECT addTraduction('Libellé du mode de calcul de intérêts', 'en_GB', 'Interests calculation method label');
SELECT addTraduction('Libellé du mode de calcul des intérêts à la rupture', 'en_GB', 'Interests calculation method label when breached');
SELECT addTraduction('Libellé du mode de calcul des pénalités à la rupture', 'en_GB', 'Penalties calculation method label when breached');
SELECT addTraduction('Libellé du mode de paiement intérêts', 'en_GB', 'Interests payment method label');
SELECT addTraduction('Libellé du produit d''épargne', 'en_GB', 'Savings product label');
SELECT addTraduction('Libellé du sens du compte', 'en_GB', 'Direction of account label');
SELECT addTraduction('Libellé du terme', 'en_GB', 'Term label');
SELECT addTraduction('Libellé du type de bien', 'en_GB', 'Property type label');
SELECT addTraduction('Libellé du type de durée du crédit', 'en_GB', 'Credit term type label');
SELECT addTraduction('Libellé du type de pièce comptable', 'en_GB', 'Accounting document type label');
SELECT addTraduction('Libellé guichet', 'en_GB', 'Counter label');
SELECT addTraduction('Libellé langue', 'en_GB', 'Language label');
SELECT addTraduction('Libellé localité', 'en_GB', 'City label');
SELECT addTraduction('Libellé produit de crédit', 'en_GB', 'Loan product label');
SELECT addTraduction('Libellé profil', 'en_GB', 'Profile label');
SELECT addTraduction('Libellé raison de clôture', 'en_GB', 'Reason for the closing label');
SELECT addTraduction('Libellé secteur d''activité', 'en_GB', 'Activity sector label');
SELECT addTraduction('Libellé statut de l''utilisateur', 'en_GB', 'User status label');
SELECT addTraduction('Libellé type comptable', 'en_GB', 'Accounting type label');
SELECT addTraduction('Libellé type de pièce d''identité', 'en_GB', 'Type of identity document label');
SELECT addTraduction('Libellé type de structure', 'en_GB', 'Structure type label');
SELECT addTraduction('Libellé', 'en_GB', 'Designation');
SELECT addTraduction('Liebellé Sexe', 'en_GB', 'Gender label');
SELECT addTraduction('Lieu NRC', 'en_GB', 'NRC place');
SELECT addTraduction('Lieu de délivrance de la pièce d''identité', 'en_GB', 'Delivery location of identity document');
SELECT addTraduction('Lieu de naissance de la relation', 'en_GB', 'Birth place of the relationship');
SELECT addTraduction('Lieu de naissance', 'en_GB', 'Birth place');
SELECT addTraduction('Lieu de pièce d''identité', 'en_GB', 'Identity document place');
SELECT addTraduction('Lieu dépôt greffe', 'en_GB', 'Location of filing at the Registry');
SELECT addTraduction('Limitation', 'en_GB', 'Limitation');
SELECT addTraduction('Localisation 1', 'en_GB', 'Localization 1');
SELECT addTraduction('Localisation 2', 'en_GB', 'Localization 2');
SELECT addTraduction('Localisation 3', 'en_GB', 'Localization 3');
SELECT addTraduction('Localisations 1', 'en_GB', 'Localizations 1');
SELECT addTraduction('Logs', 'en_GB', 'Logs');
SELECT addTraduction('Mandats', 'en_GB', 'Mandates');
SELECT addTraduction('Marge de tolérance de la rémunération', 'en_GB', 'Remuneration allowance');
SELECT addTraduction('Max jours pénalités', 'en_GB', 'Max days penalties');
SELECT addTraduction('Mode de calcul d''interêt', 'en_GB', 'Interest calculation method');
SELECT addTraduction('Mode de calcul des garanties', 'en_GB', 'Guarantees calculation method');
SELECT addTraduction('Mode de calcul des intérêts sur compte d''épargne', 'en_GB', 'Savings account interest calculation method');
SELECT addTraduction('Mode de calcul des intérêts sur le crédit', 'en_GB', 'Loan interest calculation method');
SELECT addTraduction('Mode de calcul des intérêts à la rupture', 'en_GB', 'Interests calculation method when breached');
SELECT addTraduction('Mode de calcul des pénalités à la rupture', 'en_GB', 'Penalties calculation method when breached');
SELECT addTraduction('Mode de calcul des pénalités', 'en_GB', 'Penalties calculation method');
SELECT addTraduction('Mode de paiement d''interêt', 'en_GB', 'Interest payment method');
SELECT addTraduction('Mode de paiement des intérêts sur compte d''épargne', 'en_GB', 'Savings account interest payment method');
SELECT addTraduction('Mode de perception des intérêts', 'en_GB', 'Interest collection method');
SELECT addTraduction('Mois', 'en_GB', 'Month');
SELECT addTraduction('Moment perception des frais, commissions et assurances', 'en_GB', 'Collection of fees');
SELECT addTraduction('Moment prélèvement frais dossier', 'en_GB', 'File fees withdrawal');
SELECT addTraduction('Montant bloqué', 'en_GB', 'Amount blocked');
SELECT addTraduction('Montant capital remboursé', 'en_GB', 'Capital reimbursed amount');
SELECT addTraduction('Montant capital à rembourser', 'en_GB', 'Capital amount to reimburse');
SELECT addTraduction('Montant commission virement ', 'en_GB', 'Commission amount on transfer');
SELECT addTraduction('Montant d''assurance', 'en_GB', 'Insurance amount');
SELECT addTraduction('Montant de garantie à constituer en cours ', 'en_GB', 'Amount of securities in process');
SELECT addTraduction('Montant de la commission', 'en_GB', 'Commission amount');
SELECT addTraduction('Montant de pénalité par jour de retard', 'en_GB', 'Amount of penalty by number of days late');
SELECT addTraduction('Montant demandé', 'en_GB', 'Amount requested');
SELECT addTraduction('Montant des droits d''adhésion GI', 'en_GB', 'Amount of the GI subscription fees');
SELECT addTraduction('Montant des droits d''adhésion GS', 'en_GB', 'Amount of the GS subscription fees');
SELECT addTraduction('Montant des droits d''adhésion PM', 'en_GB', 'Amount of the PM subscription fees');
SELECT addTraduction('Montant des droits d''adhésion PP', 'en_GB', 'Amount of the PP subscription fees');
SELECT addTraduction('Montant des frais de dossier', 'en_GB', 'Amount of file fees');
SELECT addTraduction('Montant du chèque', 'en_GB', 'Check amount');
SELECT addTraduction('Montant du paiement', 'en_GB', 'Payment amount');
SELECT addTraduction('Montant garantie remboursé', 'en_GB', 'Reimbursed guarantee amount');
SELECT addTraduction('Montant garantie à rembourser', 'en_GB', 'Guarantee amount to reimburse');
SELECT addTraduction('Montant intérêts remboursé', 'en_GB', 'Reimbursed interests amount');
SELECT addTraduction('Montant intérêts à rembourser', 'en_GB', 'Interests amount to reimburse');
SELECT addTraduction('Montant maximum (0 si aucun)', 'en_GB', 'Maximum amount (0 if none)');
SELECT addTraduction('Montant minimum', 'en_GB', 'Minimum amount');
SELECT addTraduction('Montant octroyé', 'en_GB', 'Amount granted');
SELECT addTraduction('Montant ou valeur', 'en_GB', 'Amount or value');
SELECT addTraduction('Montant passé en perte', 'en_GB', 'Amount written off');
SELECT addTraduction('Montant plafond depot', 'en_GB', 'Deposit maximal amount');
SELECT addTraduction('Montant plafond retrait', 'en_GB', 'Withdrawal maximal amount');
SELECT addTraduction('Montant pénalités remboursé', 'en_GB', 'Reimbursed penalties amount');
SELECT addTraduction('Montant', 'en_GB', 'Amount');
SELECT addTraduction('Mot de passe n''expire jamais ?', 'en_GB', 'Password never expires?');
SELECT addTraduction('Mot de passe', 'en_GB', 'Password');
SELECT addTraduction('Motif de l''état du dossier de crédit', 'en_GB', 'Reasons for state of the loan file.');
SELECT addTraduction('Motif de la défection', 'en_GB', 'Motive for the abandonment');
SELECT addTraduction('Motif', 'en_GB', 'Motive');
SELECT addTraduction('N* Etat d''une garantie', 'en_GB', 'Guarantee status number');
SELECT addTraduction('N* Etat du client', 'en_GB', 'Client status number');
SELECT addTraduction('N* Etats d''un dossier de crédit', 'en_GB', 'Loan file status number');
SELECT addTraduction('N*', 'en_GB', 'Number');
SELECT addTraduction('Nationalité', 'en_GB', 'Nationality');
SELECT addTraduction('Nature de l''acte d''agrément', 'en_GB', 'Nature of the act of accreditation');
SELECT addTraduction('Nature juridique', 'en_GB', 'Legal nature');
SELECT addTraduction('Nbre de jours maximum', 'en_GB', 'Maximum number of days');
SELECT addTraduction('Nbre de jours minimum', 'en_GB', 'Minimum number of days');
SELECT addTraduction('Nbre de mois max', 'en_GB', 'Max number of months');
SELECT addTraduction('Nbre de mois min.', 'en_GB', 'Min number of months');
SELECT addTraduction('Nom agence', 'en_GB', 'Agency name');
SELECT addTraduction('Nom de la langue', 'en_GB', 'Language name');
SELECT addTraduction('Nom de la relation', 'en_GB', 'Relationship name');
SELECT addTraduction('Nom du groupe', 'en_GB', 'Group name');
SELECT addTraduction('Nom', 'en_GB', 'Name');
SELECT addTraduction('Nombre d''IMF', 'en_GB', 'IMF number');
SELECT addTraduction('Nombre d''enfants', 'en_GB', 'Number of children');
SELECT addTraduction('Nombre d''occurences permises (0 si aucune limite)', 'en_GB', 'Number of allowed occurrences (0 if no limit)');
SELECT addTraduction('Nombre de banques', 'en_GB', 'Number of banks');
SELECT addTraduction('Nombre de chèques dans le chéquier commandé', 'en_GB', 'Number of checks in the ordered check book');
SELECT addTraduction('Nombre de crédits', 'en_GB', 'Number of loans');
SELECT addTraduction('Nombre de groupes solidaires maximum pour un client', 'en_GB', 'Maximum number of solidarity groups for a client');
SELECT addTraduction('Nombre de jours (-1 si dernier état)', 'en_GB', 'Number of days (-1 if latest status)');
SELECT addTraduction('Nombre de jours compte bloqué', 'en_GB', 'Number of days account blocked');
SELECT addTraduction('Nombre de jours de report pour un crédit', 'en_GB', 'Number of days for a credit carried-over');
SELECT addTraduction('Nombre de jours de report pour un débit', 'en_GB', 'Maximum number of days for a debit carried-over');
SELECT addTraduction('Nombre de jours', 'en_GB', 'Number of days');
SELECT addTraduction('Nombre de membres du groupe', 'en_GB', 'Number of members in group');
SELECT addTraduction('Nombre de parts sociales', 'en_GB', 'Number of shares');
SELECT addTraduction('Nombre de prolongations déjà effectuées', 'en_GB', 'Number of extensions already carried out');
SELECT addTraduction('Nombre de réechelonnements autorisés', 'en_GB', 'Number of authorized rescheduling');
SELECT addTraduction('Nombre de rééchelonnements', 'en_GB', 'Number of rescheduling');
SELECT addTraduction('Nombre total de part sociales', 'en_GB', 'Total number of shares');
SELECT addTraduction('Normes de calcul de provisions', 'en_GB', 'Provisions calculation standards');
SELECT addTraduction('Nouvelle durée', 'en_GB', 'New duration');
SELECT addTraduction('Num catégorie PM', 'en_GB', 'PM Category number');
SELECT addTraduction('Num du compte comptable', 'en_GB', 'Accounting account number');
SELECT addTraduction('Numero classe comptable', 'en_GB', 'Accounting class number');
SELECT addTraduction('Numero compte comptable', 'en_GB', 'Accounting account number');
SELECT addTraduction('Numéro Registre du Commerce', 'en_GB', 'Trade Register number');
SELECT addTraduction('Numéro crédit', 'en_GB', 'Loan number');
SELECT addTraduction('Numéro d''agrément/convention', 'en_GB', 'Approval/convention number');
SELECT addTraduction('Numéro d''exercice', 'en_GB', 'Fiscal year number');
SELECT addTraduction('Numéro d''identification national', 'en_GB', 'National identification number');
SELECT addTraduction('Numéro de certification', 'en_GB', 'Certification number');
SELECT addTraduction('Numéro de compte comptable', 'en_GB', 'Accounting account number');
SELECT addTraduction('Numéro de compte de vente à perte', 'en_GB', 'Loss on sale account number');
SELECT addTraduction('Numéro de compte des commissions de change', 'en_GB', 'Exchange commissions account number');
SELECT addTraduction('Numéro de compte des produits jeu sur taux', 'en_GB', 'Variation of exchange rate products account number');
SELECT addTraduction('Numéro de compte', 'en_GB', 'Account number');
SELECT addTraduction('Numéro de l''acte d''agrément', 'en_GB', 'Act of accreditation number');
SELECT addTraduction('Numéro de l''attente', 'en_GB', 'Hold number');
SELECT addTraduction('Numéro de pièce d''identité', 'en_GB', 'Identity document number');
SELECT addTraduction('Numéro de pièce', 'en_GB', 'Document number');
SELECT addTraduction('Numéro de téléphone', 'en_GB', 'Telephone number');
SELECT addTraduction('Numéro dernier chèque', 'en_GB', 'Last check number');
SELECT addTraduction('Numéro du chèque', 'en_GB', 'Check number');
SELECT addTraduction('Numéro du client', 'en_GB', 'Client number');
SELECT addTraduction('Numéro du compte de résultat', 'en_GB', 'Profit and loss account number');
SELECT addTraduction('Numéro du compte principal', 'en_GB', 'Main account number');
SELECT addTraduction('Numéro du dossier', 'en_GB', 'File number');
SELECT addTraduction('Numéro du mode de calcul des intérêts à la rupture', 'en_GB', 'Interests calculation method number when breached number');
SELECT addTraduction('Numéro du mode de calcul des pénalités à la rupture', 'en_GB', 'Penalties calculation method number when breached');
SELECT addTraduction('Numéro du parent', 'en_GB', 'Parent number');
SELECT addTraduction('Numéro', 'en_GB', 'Number');
SELECT addTraduction('N° Etat civil', 'en_GB', 'Civil status number');
SELECT addTraduction('N° Etat crédit', 'en_GB', 'Credit status number');
SELECT addTraduction('N° Etat d''un compte d''épargne', 'en_GB', 'Savings account status number');
SELECT addTraduction('N° Fonctions systèmes', 'en_GB', 'System functions number');
SELECT addTraduction('N° IBAN du compte', 'en_GB', 'Account IBAN number');
SELECT addTraduction('N° IBAN', 'en_GB', 'IBAN number');
SELECT addTraduction('N° Mode de calcul des garanties', 'en_GB', 'Guarantees calculation method number');
SELECT addTraduction('N° Mode de calcul des intérêts sur le crédit', 'en_GB', 'Loan interest calculation method number');
SELECT addTraduction('N° Mode de calcul des pénalités', 'en_GB', 'Penalties calculation method number');
SELECT addTraduction('N° Mode de calcul intérêt', 'en_GB', 'Interest calculation method number');
SELECT addTraduction('N° Mode de paiement intérêt', 'en_GB', 'Interest payment method number');
SELECT addTraduction('N° Qualité Client', 'en_GB', 'Client quality number');
SELECT addTraduction('N° Raison clôture', 'en_GB', 'Closing reason number');
SELECT addTraduction('N° Sexe', 'en_GB', 'Gender number');
SELECT addTraduction('N° Statut juridique', 'en_GB', 'Legal status number');
SELECT addTraduction('N° Type comptable', 'en_GB', 'Accounting type number');
SELECT addTraduction('N° Type de calcul de provision', 'en_GB', 'Provision calculation type number');
SELECT addTraduction('N° Type de périodicité de remboursement', 'en_GB', 'Reimbursement periodicity type number');
SELECT addTraduction('N° Types d''opérations (Table hist)', 'en_GB', 'Operations types (Table history)');
SELECT addTraduction('N° Types de garanties', 'en_GB', 'Security types number');
SELECT addTraduction('N° Types de relations', 'en_GB', 'Relationships types number');
SELECT addTraduction('N° Utilisateur', 'en_GB', 'User number');
SELECT addTraduction('N° categorie compte', 'en_GB', 'Account category number');
SELECT addTraduction('N° client', 'en_GB', 'Client No.');
SELECT addTraduction('N° compte de base', 'en_GB', 'Basic account number');
SELECT addTraduction('N° compte', 'en_GB', 'Account number');
SELECT addTraduction('N° de compte comptable', 'en_GB', 'Accounting account number');
SELECT addTraduction('N° de compte', 'en_GB', 'Account number');
SELECT addTraduction('N° de fax', 'en_GB', 'Fax number');
SELECT addTraduction('N° de l''historique', 'en_GB', 'History number');
SELECT addTraduction('N° de la relation (si client)', 'en_GB', 'Relationship number (if client)');
SELECT addTraduction('N° de pièce d''identité', 'en_GB', 'Identity document number');
SELECT addTraduction('N° de portable', 'en_GB', 'Cell phone number');
SELECT addTraduction('N° de téléphone 2', 'en_GB', 'Telephone number 2');
SELECT addTraduction('N° de téléphone 3', 'en_GB', 'Telephone number 3');
SELECT addTraduction('N° de téléphone', 'en_GB', 'Telephone number');
SELECT addTraduction('N° devise', 'en_GB', 'Currency number');
SELECT addTraduction('N° dossier', 'en_GB', 'File number');
SELECT addTraduction('N° du client', 'en_GB', 'Client number');
SELECT addTraduction('N° etat compte', 'en_GB', 'Account status number');
SELECT addTraduction('N° etat journal', 'en_GB', 'Journal status number');
SELECT addTraduction('N° guichet', 'en_GB', 'Counter number');
SELECT addTraduction('N° identificateur', 'en_GB', 'Identifier number');
SELECT addTraduction('N° langue', 'en_GB', 'Language number');
SELECT addTraduction('N° localité', 'en_GB', 'City number');
SELECT addTraduction('N° produit d''épargne', 'en_GB', 'Savings products number');
SELECT addTraduction('N° profil d''accès', 'en_GB', 'Access profile number');
SELECT addTraduction('N° profil', 'en_GB', 'Profile number');
SELECT addTraduction('N° remboursement', 'en_GB', 'Reimbursement number');
SELECT addTraduction('N° secteur d''activité', 'en_GB', 'Activity sector number');
SELECT addTraduction('N° sens compte', 'en_GB', 'Account direction number');
SELECT addTraduction('N° statut utilisateur', 'en_GB', 'User status number');
SELECT addTraduction('N° tireur/bénéficiaire', 'en_GB', 'Drawer/beneficiary number');
SELECT addTraduction('N° type de pièce d''identité', 'en_GB', 'Identity document type number');
SELECT addTraduction('N° type structure', 'en_GB', 'Structure type number');
SELECT addTraduction('N° échéance théorique', 'en_GB', 'Notional due date number');
SELECT addTraduction('N° échéance', 'en_GB', 'Due date number');
SELECT addTraduction('N° état exercice', 'en_GB', 'Fiscal year number');
SELECT addTraduction('N°type de durée du crédit', 'en_GB', 'Loan duration type');
SELECT addTraduction('Objet de la demande', 'en_GB', 'Purpose of the request ');
SELECT addTraduction('Objets de crédit', 'en_GB', 'Credit purposes');
SELECT addTraduction('Octroi de crédits à des clients auxiliaires', 'en_GB', 'Loan granting to auxiliary clients');
SELECT addTraduction('Orde de remboursement du crédit', 'en_GB', 'Loan reimbursement order');
SELECT addTraduction('Ordre de remboursement du crédit', 'en_GB', 'Loan reimbursement order');
SELECT addTraduction('Ordre de remboursement', 'en_GB', 'Reimbursement order');
SELECT addTraduction('Paiement parts sociales par groupes solidaires', 'en_GB', 'Payment of shares by solidarity groups');
SELECT addTraduction('Passage en perte automatique', 'en_GB', 'Automatic write off');
SELECT addTraduction('Patrimoine', 'en_GB', 'Estate');
SELECT addTraduction('Payement par tranche des frais adhésions', 'en_GB', 'Installment payments of subscription fees');
SELECT addTraduction('Payement par tranche des parts sociales', 'en_GB', 'Installment payment of shares');
SELECT addTraduction('Pays de naissance', 'en_GB', 'Country of birth');
SELECT addTraduction('Pays de nationalité', 'en_GB', 'Country of nationality');
SELECT addTraduction('Pays', 'en_GB', 'Country');
SELECT addTraduction('Perception des frais, commissions et assurances', 'en_GB', 'Collection of fees');
SELECT addTraduction('Personnes extérieures', 'en_GB', 'External persons');
SELECT addTraduction('Pièce justificative', 'en_GB', 'Supporting document');
SELECT addTraduction('Plafond depot au guichet', 'en_GB', 'Counter ceiling deposit');
SELECT addTraduction('Plafond retrait au guichet', 'en_GB', 'Counter ceiling withdrawal');
SELECT addTraduction('Pourcentage commission virement ', 'en_GB', 'Commission percentage on transfer');
SELECT addTraduction('Pourcentage de commission de change', 'en_GB', 'Exchange commission percentage');
SELECT addTraduction('Pourcentage de commission', 'en_GB', 'Commission percentage');
SELECT addTraduction('Pourcentage de pénalité', 'en_GB', 'Penalty percentage');
SELECT addTraduction('Pourcentage de taxe sur la commission de change', 'en_GB', 'Tax percentage on exchange commission');
SELECT addTraduction('Pouvoir de signature ?', 'en_GB', 'Signature authority?');
SELECT addTraduction('Produit compte associé au crédit', 'en_GB', 'Associated account product with credit balance');
SELECT addTraduction('Produit compte associé à l''épargne nantie', 'en_GB', 'Associated account product to pledged savings');
SELECT addTraduction('Produit d''épargne', 'en_GB', 'Savings product');
SELECT addTraduction('Produit de crédit', 'en_GB', 'Loan product');
SELECT addTraduction('Produit du compte de base', 'en_GB', 'Basic account product');
SELECT addTraduction('Produit du compte de parts sociales', 'en_GB', 'Shares account product');
SELECT addTraduction('Produit épargne', 'en_GB', 'Savings product');
SELECT addTraduction('Profil d''accès', 'en_GB', 'Access profile');
SELECT addTraduction('Profil', 'en_GB', 'Profile');
SELECT addTraduction('Profils', 'en_GB', 'Profiles');
SELECT addTraduction('Prolongeable', 'en_GB', 'Extensible');
SELECT addTraduction('Provisionner ?', 'en_GB', 'Provisioning?');
SELECT addTraduction('Provisions', 'en_GB', 'Provisions');
SELECT addTraduction('Précision de la devise', 'en_GB', 'Determining the currency');
SELECT addTraduction('Prélèvement automatique autorisé?', 'en_GB', 'Authorized automatic withdrawal?');
SELECT addTraduction('Prélèvement frais dossier', 'en_GB', 'File fees withdrawal');
SELECT addTraduction('Prénom de la relation', 'en_GB', 'Relationship first name');
SELECT addTraduction('Prénom', 'en_GB', 'First name');
SELECT addTraduction('Prénoms', 'en_GB', 'First names');
SELECT addTraduction('Pénalités constantes', 'en_GB', 'Constant penalties');
SELECT addTraduction('Pénalités proportionnelles', 'en_GB', 'Proportional penalties');
SELECT addTraduction('Pénalités suspendues?', 'en_GB', 'Penalties suspended?');
SELECT addTraduction('Période de validité du découvert (en mois)', 'en_GB', 'Period overdraft valid (in months)');
SELECT addTraduction('Périodicité', 'en_GB', 'Periodicity');
SELECT addTraduction('Qualité Client', 'en_GB', 'Client quality');
SELECT addTraduction('Qualité', 'en_GB', 'Quality');
SELECT addTraduction('Raison blocage', 'en_GB', 'Reason for blocking');
SELECT addTraduction('Raison clôture', 'en_GB', 'Closing reason');
SELECT addTraduction('Raison de clôture', 'en_GB', 'Reason for the closing');
SELECT addTraduction('Raison sociale', 'en_GB', 'Corporate name');
SELECT addTraduction('Raisons de défection d''un client', 'en_GB', 'Reasons of abandonment by a client');
SELECT addTraduction('Rejeté ?', 'en_GB', 'Rejected?');
SELECT addTraduction('Relation valide ?', 'en_GB', 'Valid relationship?');
SELECT addTraduction('Relations entre clients', 'en_GB', 'Relationships between clients');
SELECT addTraduction('Remarque', 'en_GB', 'Remark');
SELECT addTraduction('Remboursement par compte de garantie', 'en_GB', 'Reimbursement by guarantee account');
SELECT addTraduction('Report d''arrondi sur la dernière échéance', 'en_GB', 'Round sum brought forward on last due date');
SELECT addTraduction('Responsable du groupe', 'en_GB', 'Person responsible for the group');
SELECT addTraduction('Responsable', 'en_GB', 'Responsible');
SELECT addTraduction('Retrait unique ?', 'en_GB', 'Unique withdrawal?');
SELECT addTraduction('Revenu annuel', 'en_GB', 'Annual income');
SELECT addTraduction('Schemas comptable', 'en_GB', 'Financial schemas');
SELECT addTraduction('Secteur d''activité', 'en_GB', 'Activity sector');
SELECT addTraduction('Sens (in/out)', 'en_GB', 'Direction (in/out)');
SELECT addTraduction('Sens du compte', 'en_GB', 'Account direction');
SELECT addTraduction('Sens du mouvement', 'en_GB', 'Transaction direction');
SELECT addTraduction('Sens naturel', 'en_GB', 'Natural direction');
SELECT addTraduction('Sens', 'en_GB', 'Direction');
SELECT addTraduction('Service financier?', 'en_GB', 'Financial service?');
SELECT addTraduction('Sessions actives', 'en_GB', 'Active sessions');
SELECT addTraduction('Seuil de rémunération Dépôt à vue', 'en_GB', 'Demand deposit remuneration threshold');
SELECT addTraduction('Sexe', 'en_GB', 'Gender');
SELECT addTraduction('Solde ', 'en_GB', 'Balance');
SELECT addTraduction('Solde capital', 'en_GB', 'Capital balance');
SELECT addTraduction('Solde garantie', 'en_GB', 'Guarantee balance');
SELECT addTraduction('Solde intérêts', 'en_GB', 'Interest calculation balance');
SELECT addTraduction('Solde pénalités', 'en_GB', 'Penalties balance');
SELECT addTraduction('Solde utilisé pour le calcul des intérêts', 'en_GB', 'Basis for calculating the interests');
SELECT addTraduction('Solde', 'en_GB', 'Balance');
SELECT addTraduction('Statut ', 'en_GB', 'Status');
SELECT addTraduction('Statut de l''agence', 'en_GB', 'Agency status');
SELECT addTraduction('Statut de l''utilisateur', 'en_GB', 'User status');
SELECT addTraduction('Statut du transfert étranger', 'en_GB', 'Status of foreign transfer');
SELECT addTraduction('Statut juridique', 'en_GB', 'Legal status');
SELECT addTraduction('Suivi des remboursements', 'en_GB', 'Reimbursements follow-up');
SELECT addTraduction('Table contenant tous les biens des clients', 'en_GB', 'Table containing all clients'' properties');
SELECT addTraduction('Table contiendra des garanties (matérielles ou numéraires)', 'en_GB', 'Table will contain (material or cash) securities');
SELECT addTraduction('Table des agences', 'en_GB', 'Agencies table');
SELECT addTraduction('Table des comptes comptables internes à l''agence', 'en_GB', 'Table of the accounting accounts specific to the agency');
SELECT addTraduction('Taux d''intérêt', 'en_GB', 'Interest rate');
SELECT addTraduction('Taux de Provision', 'en_GB', 'Rate of provision');
SELECT addTraduction('Taux de change pour l''achat de la devise cash', 'en_GB', 'Rate of exchange for the purchase of cash currency');
SELECT addTraduction('Taux de change pour l''achat de la devise transfert', 'en_GB', 'Rate of exchange for the purchase of transfer currency');
SELECT addTraduction('Taux de change pour la vente de la devise cash', 'en_GB', 'Rate of exchange for selling of cash currency');
SELECT addTraduction('Taux de change pour la vente de la devise transfert', 'en_GB', 'Rate of exchange for selling of transfer currency');
SELECT addTraduction('Taux de change', 'en_GB', 'Rate of exchange');
SELECT addTraduction('Taux mensuel d''intéret débiteur', 'en_GB', 'Monthly interest rate charge');
SELECT addTraduction('Terme (mois, 0 si aucun)', 'en_GB', 'Term (month)');
SELECT addTraduction('Termes d''un crédit', 'en_GB', 'Loan terms');
SELECT addTraduction('Timeout (minutes)', 'en_GB', 'Timeout (minutes)');
SELECT addTraduction('Tireur', 'en_GB', 'Drawer');
SELECT addTraduction('Tireur/Bénéficiaire', 'en_GB', 'Drawer/Beneficiary');
SELECT addTraduction('Tireurs/Bénéficiaires', 'en_GB', 'Drawers/Beneficiaries');
SELECT addTraduction('Type bien', 'en_GB', 'Property type');
SELECT addTraduction('Type comptable des comptes', 'en_GB', 'Account accounting type');
SELECT addTraduction('Type de calcul de provision', 'en_GB', 'Provision calculation type');
SELECT addTraduction('Type de compte', 'en_GB', 'Type of account');
SELECT addTraduction('Type de duree du credit', 'en_GB', 'Loan duration type');
SELECT addTraduction('Type de durée du crédit', 'en_GB', 'Loan duration type');
SELECT addTraduction('Type de fonction', 'en_GB', 'Function type');
SELECT addTraduction('Type de numerotation de compte', 'en_GB', 'Account numbering type');
SELECT addTraduction('Type de pièce d''identité', 'en_GB', 'Type of identity document');
SELECT addTraduction('Type de pièce justificative', 'en_GB', 'Supporting document type');
SELECT addTraduction('Type de pièce présentée', 'en_GB', 'Type of submitted document');
SELECT addTraduction('Type de pièce', 'en_GB', 'Type of document');
SELECT addTraduction('Type de pourcentage de pénalité', 'en_GB', 'Penalty percentage type');
SELECT addTraduction('Type de pouvoir de signature', 'en_GB', 'Type of signature authority');
SELECT addTraduction('Type de produit de crédit', 'en_GB', 'Type of loan product');
SELECT addTraduction('Type de pénalité en pourcentage', 'en_GB', 'Penalty type in percentage');
SELECT addTraduction('Type de périodicité de remboursement', 'en_GB', 'Reimbursement periodicity type');
SELECT addTraduction('Type de relation', 'en_GB', 'Relationship type');
SELECT addTraduction('Type de report jours fériés', 'en_GB', 'Deferred legal holiday type');
SELECT addTraduction('Type de structure', 'en_GB', 'Structure type');
SELECT addTraduction('Type de structures', 'en_GB', 'Structures type');
SELECT addTraduction('Type garantie', 'en_GB', 'Guarantee type');
SELECT addTraduction('Type opération', 'en_GB', 'Type of operation');
SELECT addTraduction('Type pièce d''identité', 'en_GB', 'Identity document type');
SELECT addTraduction('Types d''opérations (Table hist)', 'en_GB', 'Operations types (Table history)');
SELECT addTraduction('Types de biens matériels acceptés', 'en_GB', 'Type of accepted material properties');
SELECT addTraduction('Types de billets et pièces', 'en_GB', 'Types of bank notes and coins');
SELECT addTraduction('Types de comptes pour l''historique', 'en_GB', 'Types of accounts for history');
SELECT addTraduction('Types de garanties', 'en_GB', 'Security types');
SELECT addTraduction('Types de relations', 'en_GB', 'Relationships types');
SELECT addTraduction('Types de reports pour opérations échéant un jour férié', 'en_GB', 'Types of carried over operations due on a legal holiday');
SELECT addTraduction('Téléphone', 'en_GB', 'Telephone');
SELECT addTraduction('Utilisateur créateur', 'en_GB', 'User creator');
SELECT addTraduction('Utilisateur modificateur', 'en_GB', 'User modifier');
SELECT addTraduction('Utilisateur', 'en_GB', 'User');
SELECT addTraduction('Utilisateurs', 'en_GB', 'Users');
SELECT addTraduction('Utilise imprimante matricielle ?', 'en_GB', 'Uses dot-matrix printer?');
SELECT addTraduction('Utilise interface Netbank ?', 'en_GB', 'Uses Netbank interface?');
SELECT addTraduction('Valeur de la devise', 'en_GB', 'Value of the currency');
SELECT addTraduction('Valeur estimée', 'en_GB', 'Estimated value');
SELECT addTraduction('Valeur nominale d''une part sociale', 'en_GB', 'Nominal value of a share');
SELECT addTraduction('Validité', 'en_GB', 'Validity');
SELECT addTraduction('Ville', 'en_GB', 'City');
SELECT addTraduction('catégorie de groupe solidaire', 'en_GB', 'Solidarity group category');
SELECT addTraduction('libel', 'en_GB', 'Designation');
SELECT addTraduction('libellé', 'en_GB', 'Designation');
SELECT addTraduction('nombre de caractère minimum du mot de passe', 'en_GB', 'Minimum character number in the password');
SELECT addTraduction('nombre max. des parts sociales  par client', 'en_GB', 'Maximum number of shares per client');
SELECT addTraduction('sens operation', 'en_GB', 'Operation direction');
SELECT addTraduction('type numérotation compte', 'en_GB', 'Account numbering type');
SELECT addTraduction('Nom du fichier (*.jrxml)', 'en_GB', 'Filename (*.jrxml)');
SELECT addTraduction('Code ', 'en_GB', 'Code');
SELECT addTraduction('Type ', 'en_GB', 'Type');

-- Original strings coming from db/Dump/arrete_compte.sql
SELECT addTraduction('intérêts pour le mois écoulé', 'en_GB', '');

-- Original strings coming from db/Dump/menus.sql
SELECT addTraduction('Affichage', 'en_GB', '');
SELECT addTraduction('Association taxe', 'en_GB', '');
SELECT addTraduction('Calcul provision', 'en_GB', '');
SELECT addTraduction('Choix d''une écriture libre', 'en_GB', '');
SELECT addTraduction('Choix période', 'en_GB', '');
SELECT addTraduction('Confirmation déclaration tva', 'en_GB', '');
SELECT addTraduction('Confirmation édition', 'en_GB', '');
SELECT addTraduction('Demande Confirmation', 'en_GB', '');
SELECT addTraduction('Déclaration tva', 'en_GB', '');
SELECT addTraduction('Déclarations de tva', 'en_GB', '');
SELECT addTraduction('Edition de déclaration tva', 'en_GB', '');
SELECT addTraduction('Gestion de jasper report', 'en_GB', '');
SELECT addTraduction('Gestion des écritures libres', 'en_GB', '');
SELECT addTraduction('Mise en opposition', 'en_GB', '');
SELECT addTraduction('Modification écriture libre', 'en_GB', '');
SELECT addTraduction('Saisie  écriture libre', 'en_GB', '');
SELECT addTraduction('Suppression écriture libre', 'en_GB', '');

-- Original strings coming from db/Dump/start.sql
SELECT addTraduction('Bordereau', 'en_GB', '');
SELECT addTraduction('Chèque extérieur', 'en_GB', '');
SELECT addTraduction('Autorisation de retrait sans livret/chèque', 'en_GB', '');
SELECT addTraduction('Chèque guichet', 'en_GB', '');
SELECT addTraduction('Contrat', 'en_GB', '');
SELECT addTraduction('Envoi argent', 'en_GB', '');
SELECT addTraduction('Espèce', 'en_GB', '');
SELECT addTraduction('Extrait de compte', 'en_GB', '');
SELECT addTraduction('Facture', 'en_GB', '');
SELECT addTraduction('Mise à disposition', 'en_GB', '');
SELECT addTraduction('Opération Diverse', 'en_GB', '');
SELECT addTraduction('Ordre de paiement', 'en_GB', '');
SELECT addTraduction('Ordre permanent', 'en_GB', '');
SELECT addTraduction('Reçu ADbanking', 'en_GB', '');
SELECT addTraduction('Reçu externe', 'en_GB', '');
SELECT addTraduction('Travelers cheque', 'en_GB', '');

-- Original strings coming from db/Dump/tableliste.sql
SELECT addTraduction('Accède au solde des comptes d''épargne?', 'en_GB', '');
SELECT addTraduction('Ajout paramètre', 'en_GB', '');
SELECT addTraduction('Association des opérations aux taxes', 'en_GB', '');
SELECT addTraduction('Code rapport', 'en_GB', '');
SELECT addTraduction('Commentaires sur le client', 'en_GB', '');
SELECT addTraduction('Compte de la taxe collectée', 'en_GB', '');
SELECT addTraduction('Compte de la taxe récupérée', 'en_GB', '');
SELECT addTraduction('Compte de tva à décaisser', 'en_GB', '');
SELECT addTraduction('Compte de tva à reporter', 'en_GB', '');
SELECT addTraduction('Date début période', 'en_GB', '');
SELECT addTraduction('Date fin période', 'en_GB', '');
SELECT addTraduction('Durée minimale du mot de passe (en jours, 0 si aucun)', 'en_GB', '');
SELECT addTraduction('Déclaration de tva', 'en_GB', '');
SELECT addTraduction('ID de l''opération', 'en_GB', '');
SELECT addTraduction('ID de la déclaration de tva', 'en_GB', '');
SELECT addTraduction('ID de la taxe', 'en_GB', '');
SELECT addTraduction('Libellé de la taxe', 'en_GB', '');
SELECT addTraduction('Masquer solde?', 'en_GB', '');
SELECT addTraduction('Montant assurance', 'en_GB', '');
SELECT addTraduction('Montant de la tva à décaisser', 'en_GB', '');
SELECT addTraduction('Montant de la tva à reporter', 'en_GB', '');
SELECT addTraduction('Nombre de jours (-1 si dernier état, -2 si état à radier)', 'en_GB', '');
SELECT addTraduction('Numéro TVA', 'en_GB', '');
SELECT addTraduction('Pourcentage des frais de dossier', 'en_GB', '');
SELECT addTraduction('Réalisation garantie crédits sains ?', 'en_GB', '');
SELECT addTraduction('Taxes', 'en_GB', '');
SELECT addTraduction('Type de la taxe', 'en_GB', '');
SELECT addTraduction('Type de taxe', 'en_GB', '');
SELECT addTraduction('libellé du rapport', 'en_GB', '');
SELECT addTraduction('taux de la taxe', 'en_GB', '');

-- Original strings coming from db/Dump/menus.sql
SELECT addTraduction('Rapport transactions', 'en_GB', '');

-- Original strings coming from db/Dump/start.sql
SELECT addTraduction('Acceptation chèque externe', 'en_GB', '');
SELECT addTraduction('Ajustement du solde d''un compte d''epargne en faveur de l''IMF', 'en_GB', '');
SELECT addTraduction('Ajustement du solde d''un compte d''epargne en faveur du client', 'en_GB', '');
SELECT addTraduction('Ajustement encaisse à la baisse', 'en_GB', '');
SELECT addTraduction('Ajustement encaisse à la hausse', 'en_GB', '');
SELECT addTraduction('Annulation déboursement crédit', 'en_GB', '');
SELECT addTraduction('Annulation perception commissions de déboursement', 'en_GB', '');
SELECT addTraduction('Annulation remboursement capital sur crédits', 'en_GB', '');
SELECT addTraduction('Annulation remboursement intérêts sur crédits', 'en_GB', '');
SELECT addTraduction('Annulation remboursement pénalités', 'en_GB', '');
SELECT addTraduction('Annulation transfert des assurances', 'en_GB', '');
SELECT addTraduction('Annulation transfert des frais', 'en_GB', '');
SELECT addTraduction('Annulation transfert des garanties numéraires', 'en_GB', '');
SELECT addTraduction('Approvisionnement guichet', 'en_GB', '');
SELECT addTraduction('Augmentation capital suite à rééch/moratoire sur crédit ', 'en_GB', '');
SELECT addTraduction('Compensation assurance', 'en_GB', '');
SELECT addTraduction('Contre régularisation suite à apurement crédit rééchelonné', 'en_GB', '');
SELECT addTraduction('Contre-passation', 'en_GB', '');
SELECT addTraduction('Déboursement crédit ', 'en_GB', '');
SELECT addTraduction('Déclassement/reclassement crédit', 'en_GB', '');
SELECT addTraduction('Délestage guichet', 'en_GB', '');
SELECT addTraduction('Dépôt agence', 'en_GB', '');
SELECT addTraduction('Dépôt au siège', 'en_GB', '');
SELECT addTraduction('Dépôt espèces', 'en_GB', '');
SELECT addTraduction('Dépôt travelers cheque', 'en_GB', '');
SELECT addTraduction('Dépôt/Payement par Carte Ferlo', 'en_GB', '');
SELECT addTraduction('Emprunt auprès du siège', 'en_GB', '');
SELECT addTraduction('Envoi OP (hors client) vers l''extérieur', 'en_GB', '');
SELECT addTraduction('Envoi chèque', 'en_GB', '');
SELECT addTraduction('Envoi d''un OP vers un correspondant', 'en_GB', '');
SELECT addTraduction('Fermeture de compte au guichet', 'en_GB', '');
SELECT addTraduction('Fermeture de compte par transfert', 'en_GB', '');
SELECT addTraduction('Frais OP (hors client) vers l''extérieur', 'en_GB', '');
SELECT addTraduction('Frais d''une mise à disposition', 'en_GB', '');
SELECT addTraduction('Frais de dossier de crédit', 'en_GB', '');
SELECT addTraduction('Frais de mise à disposition (à payer au correspondant)', 'en_GB', '');
SELECT addTraduction('Frais de refus OP (à facturer au donneur d''ordre)', 'en_GB', '');
SELECT addTraduction('Frais de refus OP (à payer au correspondant)', 'en_GB', '');
SELECT addTraduction('Frais de refus chèque (client)', 'en_GB', '');
SELECT addTraduction('Frais de refus chèque (correspondant)', 'en_GB', '');
SELECT addTraduction('Frais de transfert', 'en_GB', '');
SELECT addTraduction('Frais de virement', 'en_GB', '');
SELECT addTraduction('Gains sur arrondis prélevés sur Compte Epargne', 'en_GB', '');
SELECT addTraduction('Gains sur arrondis versés au guichet', 'en_GB', '');
SELECT addTraduction('Intégration aux produits du reste change', 'en_GB', '');
SELECT addTraduction('Intégration exceptionnelle parts sociales dans fonds propres', 'en_GB', '');
SELECT addTraduction('Intégration exceptionnelle solde du compte Garanties dans fonds propres', 'en_GB', '');
SELECT addTraduction('Intégration exceptionnelle solde du compte d''epargne dans fonds propres', 'en_GB', '');
SELECT addTraduction('Migration de fonds suite modification paramétrage des produits d''épargne', 'en_GB', '');
SELECT addTraduction('Mise en attente chèque', 'en_GB', '');
SELECT addTraduction('Mise en attente de frais', 'en_GB', '');
SELECT addTraduction('Non disponible', 'en_GB', '');
SELECT addTraduction('OP (hors client) vers l''extérieur', 'en_GB', '');
SELECT addTraduction('OP vers un compte extérieur', 'en_GB', '');
SELECT addTraduction('Opération de régularisation', 'en_GB', '');
SELECT addTraduction('Paiement d''une mise à disposition', 'en_GB', '');
SELECT addTraduction('Paiement de tva déductible', 'en_GB', '');
SELECT addTraduction('Participation aux charges du réseau', 'en_GB', '');
SELECT addTraduction('Parts sociales agence', 'en_GB', '');
SELECT addTraduction('Passage crédit en perte', 'en_GB', '');
SELECT addTraduction('Passage en perte de frais en attente', 'en_GB', '');
SELECT addTraduction('Passage en perte solde compte épargne débiteur', 'en_GB', '');
SELECT addTraduction('Perception commissions de déboursement', 'en_GB', '');
SELECT addTraduction('Perception de bénéfice sur le taux de change', 'en_GB', '');
SELECT addTraduction('Perception de commission de change', 'en_GB', '');
SELECT addTraduction('Perception de taxe de change', 'en_GB', '');
SELECT addTraduction('Perception de tva collectée', 'en_GB', '');
SELECT addTraduction('Perception des frais d''ouverture de compte', 'en_GB', '');
SELECT addTraduction('Perception des frais de chèquier', 'en_GB', '');
SELECT addTraduction('Perception des frais de dossier découvert', 'en_GB', '');
SELECT addTraduction('Perception des frais de fermeture', 'en_GB', '');
SELECT addTraduction('Perception des frais de retrait', 'en_GB', '');
SELECT addTraduction('Perception des intérets débiteurs', 'en_GB', '');
SELECT addTraduction('Perception frais de crédit direct sauf bonne fin', 'en_GB', '');
SELECT addTraduction('Perception frais de dépôt', 'en_GB', '');
SELECT addTraduction('Provisions crédits', 'en_GB', '');
SELECT addTraduction('Prêt à une agence', 'en_GB', '');
SELECT addTraduction('Pénalité rupture anticipée', 'en_GB', '');
SELECT addTraduction('Recharge Carte Ferlo par compte Epargne', 'en_GB', '');
SELECT addTraduction('Recharge Carte Ferlo par versement espèce', 'en_GB', '');
SELECT addTraduction('Recouvrement de frais en attente', 'en_GB', '');
SELECT addTraduction('Recouvrement sur crédit en perte', 'en_GB', '');
SELECT addTraduction('Recupération de la garantie numéraire', 'en_GB', '');
SELECT addTraduction('Refacturation aux agences', 'en_GB', '');
SELECT addTraduction('Refus OP (hors client) vers l''extérieur', 'en_GB', '');
SELECT addTraduction('Refus chèque', 'en_GB', '');
SELECT addTraduction('Refus d''une mise à disposition', 'en_GB', '');
SELECT addTraduction('Rejet d''un OP vers l''extérieur', 'en_GB', '');
SELECT addTraduction('Rejet d''une mise à disposition', 'en_GB', '');
SELECT addTraduction('Remboursement capital sur crédits', 'en_GB', '');
SELECT addTraduction('Remboursement crédit aux agences', 'en_GB', '');
SELECT addTraduction('Remboursement crédit du siège', 'en_GB', '');
SELECT addTraduction('Remboursement d''un OP refusé', 'en_GB', '');
SELECT addTraduction('Remboursement intérêts sur crédits', 'en_GB', '');
SELECT addTraduction('Remboursement parts sociales', 'en_GB', '');
SELECT addTraduction('Remboursement pénalités', 'en_GB', '');
SELECT addTraduction('Reprise des crédits', 'en_GB', '');
SELECT addTraduction('Reprise sur provisions crédits', 'en_GB', '');
SELECT addTraduction('Restitution de la garantie numéraire', 'en_GB', '');
SELECT addTraduction('Retrait au siège', 'en_GB', '');
SELECT addTraduction('Retrait cash par chèque', 'en_GB', '');
SELECT addTraduction('Retrait des agences', 'en_GB', '');
SELECT addTraduction('Retrait des frais de tenue de compte', 'en_GB', '');
SELECT addTraduction('Retrait en espèces', 'en_GB', '');
SELECT addTraduction('Retrait espèce par Carte Ferlo', 'en_GB', '');
SELECT addTraduction('Retrait par chèque sur compte epargne', 'en_GB', '');
SELECT addTraduction('Retrait travelers cheque', 'en_GB', '');
SELECT addTraduction('Réception chèque externe', 'en_GB', '');
SELECT addTraduction('Réception d''un chèque client', 'en_GB', '');
SELECT addTraduction('Récupération parts sociales', 'en_GB', '');
SELECT addTraduction('Régularisation suite à apurement crédit rééchelonné', 'en_GB', '');
SELECT addTraduction('Titres de participation', 'en_GB', '');
SELECT addTraduction('Transfert des garanties numéraires', 'en_GB', '');
SELECT addTraduction('Transfert du solde lié à un état de crédit d''un produit de crédit', 'en_GB', '');
SELECT addTraduction('Transfert entre comptes d''epargne', 'en_GB', '');
SELECT addTraduction('Variation négative du taux de change', 'en_GB', '');
SELECT addTraduction('Variation positive du taux de change', 'en_GB', '');
SELECT addTraduction('Vente à perte de devise', 'en_GB', '');
SELECT addTraduction('Versement au guichet du reste change', 'en_GB', '');
SELECT addTraduction('Versement des intérêts sur compte epargne', 'en_GB', '');
SELECT addTraduction('Versement sur compte de base du reste change', 'en_GB', '');
SELECT addTraduction('Virement Solde d''un compte principal', 'en_GB', '');
SELECT addTraduction('Virement banque pour le compte d''un client', 'en_GB', '');
SELECT addTraduction('Virement client sur la banque', 'en_GB', '');
SELECT addTraduction('Virement du compte de résultat', 'en_GB', '');
SELECT addTraduction('Virement national', 'en_GB', '');
SELECT addTraduction('transfert solde  d'' un compte supprimé', 'en_GB', '');

-- Original strings coming from db/Dump/tableliste.sql
SELECT addTraduction('Compte interne client', 'en_GB', '');
SELECT addTraduction('Date valeur', 'en_GB', '');
SELECT addTraduction('Ecritures comptables', 'en_GB', '');
SELECT addTraduction('Id exercice', 'en_GB', '');
SELECT addTraduction('Id transaction', 'en_GB', '');
SELECT addTraduction('Id écriture', 'en_GB', '');
SELECT addTraduction('Infos écriture', 'en_GB', '');
SELECT addTraduction('Journal', 'en_GB', '');
SELECT addTraduction('Libel écriture', 'en_GB', '');
SELECT addTraduction('Mouvements comptables', 'en_GB', '');
SELECT addTraduction('Ref écriture', 'en_GB', '');
SELECT addTraduction('Type operation', 'en_GB', '');


SELECT addTraduction('Nom du fichier (*.jrxml)', 'en_GB', 'Filename (*.jrxml)');
SELECT addTraduction('Nom du fichier (*.jrxml)', 'en_GB', 'Filename (*.jrxml)');

-- Original strings coming from db/Dump/menus.sql
SELECT addTraduction('Gestion des champs extras', 'en_GB', '');

-- Original strings coming from db/Dump/tableliste.sql
SELECT addTraduction('Champs extras', 'en_GB', '');
SELECT addTraduction('Identifiant de la table', 'en_GB', '');
SELECT addTraduction('Identifiant du champs', 'en_GB', '');
SELECT addTraduction('Libellé du champs extras', 'en_GB', '');
SELECT addTraduction('Libellé du type de champs', 'en_GB', '');
SELECT addTraduction('Type de champs', 'en_GB', '');
SELECT addTraduction('Type du champs', 'en_GB', '');
